#!/bin/bash

dim_description='The environment (e.g. e1, e2)'

# input: value result_var
# output: *result_var
expand_member() {
local result=

case "$value" in
  e1|e2|e2i|e31|e32|e33|e31i|e32i)
    result=$value
  ;;
esac

eval "$result_var='$result'"
}

# input: value result_var
# output: *result_var
expand_members() {
local result=

case "$value" in
  all)
    result='e1 e2 e2i e31 e32 e33 e31i e32i'
  ;;
  e3)
    result='e31 e32 e33'
  ;;
  e3i)
    result='e31i e32i'
  ;;
  us)
    result='e1 e2 e31 e32 e33'
  ;;
  ind*)
    result='e2i e31i e32i'
  ;;
esac

eval "$result_var='$result'"
}
