#!/bin/bash

description='The ecp project (e.g. one-data one-data-staging)'

# input: value result_var
# output: *result_var
expand_member() {
local result=

if [[ ! "$value" ]]; then 
  result=one-data
else
  case "$value" in
    od)
      result=one-data
    ;;
    ods)
      result=one-data-staging
    ;;
    odcs)
      result=one-data-core-staging
    ;;
    odcs2)
      result=one-data-core-standby
    ;;
    odcc)
      result=one-data-core-chaos
    ;;
    odct)
      result=one-data-core-test
    ;;
    odfp)
      result=one-data-functions-performance
    ;;
    oi)
      result=one-identity
    ;;
    ois)
      result=one-identity-staging
    ;;
    one-data|one-data-staging|one-data-core-chaos|one-data-core-standby|one-data-core-test|one-data-core-staging|one-data-functions-performance|one-identity|one-identity-staging)
      result=$value
    ;;
  esac
fi

eval "$result_var='$result'"
}

# input: value result_var
# output: *result_var
expand_members() {
local result=

case "$value" in
  all)
    result='one-data one-data-staging one-data-core-chaos one-data-core-standby one-data-core-test one-data-core-staging one-data-functions-performance one-identity one-identity-staging'
  ;;
esac

eval "$result_var='$result'"
}
