#!/bin/bash

set -u
# Set this to true to more easily debug the docker build process
debug=${debug:-f}

# whether to do a clean build, wiping out previous home folder and work folder
clean=${clean:-f}

# as above, but also wipes the alpine build cache (very rarely needed, and will greatly slow down the build)
deepclean=${deepclean:-f}

# Set this in order to build an image that you plan to deploy to a different architecture machine:
arch=${arch:-}

# Embeds simpleton repo into the image. Other modules must be added to the launch command manually.
embed=${embed:-f}

if [[ "${1:-}" == clean ]]; then
  clean=t
  shift
fi

if [[ "${1:-}" == deepclean ]]; then
  deepclean=t
  clean=t
  shift
fi

if [[ "${1:-}" == debug ]]; then
  debug=t
  shift
fi

if [[ -z $arch ]]; then
  build_platform=
else
  build_platform="--platform linux/$arch"
  arch=${arch}-
fi

instance=${instance:-${1:-}}

err() { echo "$*" >&2; }

if [[ ! -f build ]]; then
  err "This script must be run from within the same folder it exists in."
  exit 1
fi

SIMPLETON_BASE=${SIMPLETON_BASE:-${PWD%/*}}
SIMPLETON_REPO=$SIMPLETON_BASE/simpleton$instance
SIMPLETON_HOME=${SIMPLETON_HOME:-$HOME/.simpletonHome$instance}
SIMPLETON_WORK=${SIMPLETON_WORK:-$HOME/.simpletonWork$instance}

# Sharing the cache across instances
SIMPLETON_CACHE=${SIMPLETON_CACHE:-$HOME/.simpletonCache}

if [[ $debug == t ]]; then
  source $SIMPLETON_REPO/lib/bash-debugger || exit 1
  debug_start || exit 1
fi

if [[ $clean == t ]]; then
  if [[ -d "$SIMPLETON_HOME" ]]; then
    echo "Cleaning $SIMPLETON_HOME"
    rm -rf $SIMPLETON_HOME || exit 1
  fi
  if [[ -d "$SIMPLETON_WORK" ]]; then
    echo "Cleaning $SIMPLETON_WORK"
    rm -rf $SIMPLETON_WORK || exit 1
  fi
  if [[ -d target ]]; then
    echo "Cleaning target"
    rm -rf target || exit 1
  fi
fi

if [[ $deepclean == t ]]; then
  if [[ -d "$SIMPLETON_CACHE" ]]; then
    echo "Cleaning $SIMPLETON_CACHE"
    rm -rf "$SIMPLETON_CACHE" || exit 1
  fi
fi

if [[ ! -d $SIMPLETON_HOME ]]; then
  mkdir $SIMPLETON_HOME || exit 1
fi

if [[ ! -d $SIMPLETON_WORK ]]; then
  mkdir $SIMPLETON_WORK || exit 1
fi

if [[ ! -d $SIMPLETON_CACHE ]]; then
  mkdir $SIMPLETON_CACHE || exit 1
fi

if [[ ! "${TIME_ZONE:-}" ]]; then
  err "The TIME_ZONE env var must be set. It should be a standard linux time zone path." 
  err "Different options can be found in this path in most linux docker images: /usr/share/zoneinfo"
  err "Examples:"
  err "  export TIME_ZONE=US/Arizona"
  err "  export TIME_ZONE=US/Eastern"
  err "  export TIME_ZONE=US/Central"
  exit 1
fi

if [[ "$PWD" == *\ * ]]; then
  err "You must not have a space in the name of any parent folder of this directory: $PWD"
  err "Please put your repos in a different place or rename the parent folder to not have spaces and try again."
  exit 1
fi

repo_folders="$(find .. -mindepth 1 -maxdepth 1 | sort)"

build_dir=target
mkdir -p $build_dir || exit 1
cp docker/* $build_dir/ || exit 1

uid=$UID
user=$USER
echo "$user:x:$uid:$uid:$user:/home:/bin/bash" >>$build_dir/passwd || exit 1

repo_mount=
if [[ $embed == f ]]; then
  repo_mount='  -v $SIMPLETON_BASE:/repo \'
fi

echo -n '
launch_command="
docker run --init -it --rm -u $uid --name $name -h $name \
  -v $SIMPLETON_HOME:/home \
  -v $SIMPLETON_WORK:/work \
  '$repo_mount'
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp:/tmp \
' | tee $build_dir/launch-command-fast >$build_dir/launch-command-persist || exit 1

echo 'docker_copy_command="' >$build_dir/docker-copy-command

repo_folders="$(find .. -mindepth 1 -maxdepth 1 | sort)"

names=
for repo_folder in $repo_folders; do

  if [[ -f "$repo_folder/before-docker-build" ]]; then
    source "$repo_folder/before-docker-build" || exit 1
  fi

  if [[ -f "$repo_folder/after-Dockerfile" ]]; then
    cat $repo_folder/after-Dockerfile >>$build_dir/Dockerfile || exit 1
  fi

  if [[ -f "$repo_folder/docker-run-options" ]]; then
    cat $repo_folder/docker-run-options | tee -a $build_dir/launch-command-fast >>$build_dir/launch-command-persist || exit 1
  fi

  if [[ -d $repo_folder/seed ]]; then
    for seed in $(find $repo_folder/seed -mindepth 1 -maxdepth 1 -type d); do
      base_seed_name=${seed##*/}
      seed_name=$base_seed_name
      count=1
      while [[ $names =~ \ "$seed_name"\  ]]; do
        let count++
        seed_name=$base_seed_name$count
      done
      names+=" $seed_name "
      seed=$(readlink -f $seed)
      echo "  -v $seed:/seed/$seed_name \\" >>$build_dir/launch-command-persist || exit 1
      echo "docker cp $seed \$name:/seed/$seed_name" >>$build_dir/docker-copy-command || exit 1
    done
  fi

done

echo '  -e prompt_name=\"$name \" \
  -e USER=$user \
  -e NO_PROXY='${NO_PROXY:-}' \
  -e HTTPS_PROXY='${HTTPS_PROXY:-}' \
  -e HTTP_PROXY='${HTTP_PROXY:-}' \
  -e ADD_PATH='/repo/simpleton/bin' \
  -v $PWD/target/passwd:/etc/passwd \
  $name 
"' | tee -a $build_dir/launch-command-fast >>$build_dir/launch-command-persist || exit 1

echo '"' >>$build_dir/docker-copy-command

ALPINE_IMAGE=${ALPINE_IMAGE:-alpine:3.21.0}
ALPINE_REPO=${ALPINE_REPO:-https://dl-cdn.alpinelinux.org/alpine/}

local_alpine_image_count=$(docker image ls -q $ALPINE_IMAGE | wc -l)
if (( local_alpine_image_count == 0 )); then
  echo "Pulling $ALPINE_IMAGE to local cache to speed up future builds and remove network dependency"
  docker pull $ALPINE_IMAGE || exit 1
fi

#  This requires a later version of docker desktop that not all users may have, so will add this back later
extra=
if [[ ${use_cache:-f} == t ]]; then
  extra+="--cache-from type=local,src=$SIMPLETON_CACHE
  --cache-to type=local,dest=$SIMPLETON_CACHE
  "
fi

if [[ ${debug_build:-f} == t ]]; then
  extra+="-D
  "
fi

set -x
docker buildx build \
  $extra \
  $build_platform \
  -f $build_dir/Dockerfile \
  -t ${arch}simpleton$instance \
  -o type=docker \
  --build-arg TIME_ZONE=$TIME_ZONE \
  --build-arg ALPINE_IMAGE=$ALPINE_IMAGE \
  --build-arg ALPINE_REPO=$ALPINE_REPO \
  .
set +x

