#!/usr/bin/env bash

set -ue 

if [[ ! "${USER:-}" ]]; then
  echo "You must set env var USER to your user name" >&2
  exit 1
fi

# sed -i "s/autouser/$USER/g" /etc/passwd
# sed -i "s/99999/$UID/g" /etc/passwd
# sed -i "s/autouser/$USER/g" /etc/group
# sed -i "s/99999/$UID/g" /etc/group

if [[ ! -f ~/.ssh/id_rsa ]]; then
  if [[ ! -d ~/.ssh ]]; then
    mkdir ~/.ssh
  fi
  ssh-keygen -mPEM -f ~/.ssh/id_rsa -N "" 
fi

if [[ "${COMMAND:-}" ]]; then
  /bin/bash -lc "$COMMAND"
else
  /bin/bash -l
fi

