#!/bin/bash

# joins the existing simpleton docker container

name=${1:-simpleton}
as_root=${as_root:-f}

if [[ $as_root == t ]]; then
  set -x
  docker exec -e USER=$user -u root -it $name /bin/bash -l
  set +x
else
  set -x
  docker exec -it $name /bin/bash -l
  set +x
fi
