#!/bin/bash

if [ ! "$SIMPLETON_WORKSPACE" ]; then
  echo "You must set SIMPLETON_WORKSPACE env var to your workspace folder before running this." >&2
  exit 1
fi

set -x
docker run -it --rm -u $UID --name simpleton -e COLUMNS=$COLUMNS -v $SIMPLETON_WORKSPACE:/work -e USER=$USER simpleton
set +x
