#!/usr/bin/env bash

source $SIMPLETON_LIB/update-lib

check_command() {
  begin_function
    local data_valid=f
    if [[ $current_mock == f ]]; then
      update_upstreams || fail
      execute_op check || fail
      if [[ $data_valid == f ]]; then
        out "Data is not valid"
      else
        out "Data is valid"
      fi
    fi
    command_successful=t
  end_function
  handle_return
}

