#!/usr/bin/env bash

check_command() {
  begin_function
    local data_valid=f
    execute_op check || fail
    if [[ $data_valid == f ]]; then
      out "Data is not valid"
    else
      out "Data is valid"
    fi
    command_successful=t
  end_function
  handle_return
}

