#!/usr/bin/env bash

clean_command() {
  begin_function
    if [[ $cell_path == /seed/* ]]; then
      log_fatal "Can't clean seed paths, only work cells"
      fail1
    fi
    get_bottom_cell $cell_path || fail
    if [[ ! "$bottom_cell" ]]; then
      bottom_cell=$cell_path
    fi
    : ${clean_depth:=1} ${kind:=all}
    if [[ $cell_command == clean2 ]]; then
      kind=data
    elif [[ $cell_command == clean0 ]]; then
      kind=context
    fi
    clean_folder $bottom_cell || fail
    command_successful=t
    # to force the next command to load a new context
    last_context_loaded=
  end_function
  handle_return
}

