#!/usr/bin/env bash

dim_ls_command() {
  begin_function

    switch_context $cell_path || fail
    show_dimensions ${trunk_dims[*]} ${sub_dims[*]} ${control_props[*]} ${data_props[*]} || fail
    command_successful=t

  end_function
  handle_return
}

