#!/usr/bin/env bash

dim_ls_command() {
  begin_function

    switch_context $cell_path || fail
    show_dimensions ${trunk_dims_expanded[*]} ${sub_dims_expanded[*]} ${control_props_expanded[*]} ${data_props_expanded[*]} || fail
    command_successful=t

  end_function
  handle_return
}

