#!/usr/bin/env bash

dim_rm_delete_branches() {
  begin_function

    local seed=$1 branch sub_found=f
    local branches=$(find1 $seed -name "*:*" | sort) || fail

    begin_for branch in $branches; doo
      dim=${branch##*/}
      dim=${dim%%:*}
      dim_rm_delete_branches $branch || fail
      sub_found=t
    end_for

    if [[ $sub_found == f && $seed == *:* ]]; then
      log_info "Removing dim $dim"
      rm -rf $seed || fail
    fi

  end_function
  handle_return
}

dim_rm_command() {
  begin_function

    local seed_path trunk_seed_path
    setup_cell_path_vars $cell_path || fail
    find_seed_path $cell_path || fail
    trunk_seed_path=$seed_path

    local dim=
    dim_rm_delete_branches $seed_path || fail

    local dim_folder=$seed_path/.dna/${dim}
    if [[ -d $dim_folder ]]; then
      rm -rf $dim_folder || fail
    fi

    command_successful=t

  end_function
  handle_return
}

