#!/bin/bash

log() {
local log_file=${log_file:-}

debug_start
if [[ ! "${log_file:-}" ]]; then
  log_file=$cyto_path/job/last-attempt/log/1.olog
fi

if [[ ! -f "$log_file" ]]; then
  log_error "Log file doesn't exist: $log_file. Maybe this cell hasn't been updated yet?"
  return 1
fi

omni_navigator
}