#!/bin/bash

log() {
  local log_file=${log_file:-} log_command=${p_command:-}

  if [[ ! "${log_file:-}" ]]; then
    local job_part=last-attempt
    if [[ "${p_job_id:-}" ]]; then
      job_part=$p_job_id
    elif [[ "$log_command" ]]; then
      job_part=last-$log_command-attempt
    fi
    log_file=$job_path/$job_part/log/first.olog
  fi

  if [[ -d "$log_file/log" ]]; then
    log_file=$log_file/log/first.olog
  fi

  if [[ ! -f "$log_file" ]]; then
    log_error "Log file doesn't exist: $log_file. Maybe this cell hasn't been updated yet?"
    return 1
  fi

  omni_navigator
}
