#!/usr/bin/env bash

member_create_command() {
  begin_function

    local deep=${deep:-t}
    if [[ $cell_path == /seed/* ]]; then
      log_fatal "Can't run this command from within a seed. Run this in the workspace instead."
      fail1
    fi

    seed_path=/seed/${cell_path#/work/}

    if [[ ! -d $seed_path ]]; then
      log_fatal "No seed exists for this cell in $seed_path"
      fail1
    fi

    local f folders=$(find1 $seed_path -type d -not -name ".*" -not -name "_*" -printf "%f\n" | sort) || fail
    begin_for f in $folders; doo

      local target=$cell_path/$f

      if [[ ! -d $target ]]; then
        mkdir $target || fail
      fi
       
    end_for

    command_successful=t
  end_function
  handle_return
}

