#!/usr/bin/env bash

mock_create_command() {
  begin_function

    local mock=${mock:-} \
    local seed_path mock_path
    find_seed_path $cell_path || fail
    mock_path=$seed_path/.mock

    if [[ ! "$mock" ]]; then
      log_fatal "This should not be possible"
      fail1
    fi

    if [[ $mock == f || $mock == disabled ]]; then
      log_fatal "Can't name a mock '$mock' since that is reserved for unmocked cells"
      fail1
    fi

    if [[ -d $mock_path/$mock ]]; then
      log_fatal "A mock already exists with this name: $mock"
      fail1
    fi

    mkdir -p $mock_path/$mock || fail
    rsync -a --exclude ".*" $cell_path/ $mock_path/$mock/ || fail

    command_successful=t

  end_function
  handle_return
}

