#!/usr/bin/env bash

mock_ls_command() {
  begin_function

    local seed_path mock_path
    find_seed_path $cell_path || fail
    mock_path=$seed_path/.mock

    mocks=( $(find1 $mock_path -not -name export -printf "%f ") ) || fail
    if [[ "$mocks" ]]; then
      {
      for mock in ${mocks[*]}; do
        local -n description=mock_${mock//-/_}_description
        local output="$mock "
        if [[ "${description:-}" ]]; then
          output+="$description"
        fi
        echo "$output"
      done
      } | column -t
    else
      out "No mocks have been defined for this cell."
    fi

    command_successful=t

  end_function
  handle_return
}

