#!/usr/bin/env bash

mock_ls_command() {
  begin_function

    switch_context $cell_path || {
      log_fatal "Context failed to load for $short_cell"
      fail1
    }

    local choices=
    mock_get_choices || fail

    if [[ "${choices:-}" ]]; then
      {
      for mock in ${choices[*]}; do
        local -n description=mock_${mock//-/_}_description
        local output="$mock "
        if [[ "${description:-}" ]]; then
          output+="$description"
        fi
        echo "$output"
      done
      } | column -t -l2
    else
      out "No mocks have been defined for this cell."
    fi

    command_successful=t

  end_function
  handle_return
}

