#!/usr/bin/env bash

mock_leaf() {
  begin_function
    local mock_changed=f
    if [[ $current_mock == f ]]; then
      if [[ $mock != f ]]; then
        mock_changed=t
      else # both are f
        log_warn "Keeping previous unmocked state"
      fi
    else # current_mock != f
      if [[ $mock != f ]]; then
        if [[ $mock != $current_mock ]]; then
          mock_changed=t
        else
          log_warn "Keeping previous mock: $mock"
        fi
      else # current_mock != f && mock == f
        log_warn "Removing mock"
        rm $cell_path/.mock || fail
        kind=data clean_cell $cell_path || fail
      fi
    fi

    if [[ $mock_changed == t ]]; then
      echo "$mock" >$cell_path/.mock || fail
    fi

  end_function
  handle_return
}

mock_branch() {
  begin_function
    local branch_cells=$(find1 $cell_path -name '*:*') || fail
    local branch_cell
    begin_for branch_cell in $branch_cells; doo
      cell_path=$branch_cell
      anchor_dims=
      switch_context || fail
      mock_cell || fail
    end_for
  end_function
  handle_return
}

mock_cell() {
  begin_function
    log_info "Checking $short_cell"
    mock_leaf || fail
    if [[ $cell_is_leaf == f ]]; then
      mock_branch || fail
    fi
  end_function
  handle_return
}

mock_command() {
  begin_function

    local mock=${mock:-}

    if [[ ! "$mock" ]]; then
      if [[ -d $mock_path ]]; then
        local options=( $(find1 $mock_path -not -name export -printf "%f ") )
        if (( ${#options[*]} > 0 )); then
          choose "Which mock? " mock "${options[@]}" f || fail
        else
          log_fatal "There are no mocks available for this cell. To create one, create a folder here: $mock_path"
          fail1
        fi
      else
        log_fatal "There are no mocks available for this cell. To create one, create a folder here: $mock_path"
        fail1
      fi
    fi

    if [[ $mock != f && ! -d $mock_path/$mock ]]; then
      log_fatal "Invalid mock: $mock"
      if [[ -d $mock_path ]]; then
        local options=( $(find1 $mock_path -printf "%f") )
        if (( ${#options[*]} > 0 )); then
          log_fatal "You must choose one of these mocks: ${options[*]} or use f to unmock this cell, or just leave the mock field blank to get a menu"
        else
          log_fatal "There are no mocks available for this cell. To create one, create a folder here: $mock_path"
        fi
      else
        log_fatal "There are no mocks available for this cell. To create one, create a folder here: $mock_path"
      fi
      fail1
    fi

    mock_cell || fail

    command_successful=t

  end_function
  handle_return
}

