#!/usr/bin/env bash

plant_command() {
  begin_function

    local seed_path=/seed${cell_path#/work}
    get_key_path || fail
    plant_seed $cell_path || fail
    command_successful=t

  end_function
  handle_return
}

