#!/usr/bin/env bash

plant_command() {
  begin_function

    seed_path=/seed${cell_path#/work}

    if [[ ! -d $seed_path ]]; then
      log_fatal "No seed exists for this cell in $seed_path"
      fail1
    fi

    plant_seed $seed_path $cell_path || fail

    command_successful=t

  end_function
  handle_return
}

