#!/usr/bin/env bash

plant_command() {
  begin_function

    if [[ $cell_path == /seed/* ]]; then
      log_fatal "Can't run this command from within a seed. Run this in the workspace instead."
      fail1
    fi

    seed_path=/seed/${cell_path#/work/}

    if [[ ! -d $seed_path ]]; then
      log_fatal "No seed exists for this cell in $seed_path"
      fail1
    fi

    plant_seed $seed_path $cell_path || fail

    command_successful=t

  end_function
  handle_return
}

