#!/usr/bin/env bash

reactor_ls_command() {
  begin_function

    switch_context $cell_path || {
      log_fatal "Context failed to load for $short_cell"
      fail1
    }

    show_reactors || fail

    command_successful=t

  end_function
  handle_return
}

