#!/usr/bin/env bash

# meant to be able to execute cell commands directly as shell functions instead of running scripts
# there were problems with debugging though that haven't been resolved yet
# a bit outdated, so needs a tuneup to bring it back

shell_command() {
  begin_function
    export prompt_name='cell shell'
    bash --init-file <(
      cat \
      /etc/profile \
      $SIMPLETON_LIB/bash-lib \
      $SIMPLETON_LIB/omni-log \
      $SIMPLETON_LIB/omni-navigator \
      $SIMPLETON_LIB/bash-debugger \
      $SIMPLETON_LIB/cell-lib \
      $SIMPLETON_LIB/cell-shell-prep \
      )
  end_function
  handle_return
}
