#!/usr/bin/env bash

up_ls_command() {
  begin_function

    switch_context $cell_path || {
      log_fatal "Context failed to load for $short_cell"
      fail1
    }

    local indent=${indent:-0}
    if [[ "${dna_up_files:-}" ]]; then
      out "DNA Upstream dependencies:"
      indent=$((indent+2)) show_dna_upstreams || fail
      out "Standard Upstream cell dependencies:"
      indent=$((indent+2)) show_upstreams || fail
    else
      show_upstreams || fail
    fi

    command_successful=t

  end_function
  handle_return
}

