#!/usr/bin/env bash

main() {

  set -u

  if [[ ! "${USER:-}" ]]; then
    echo "You must set env var USER to your user name" >&2
    return 1
  fi

  if [[ ! -f ~/.ssh/id_rsa ]]; then
    if [[ ! -d ~/.ssh ]]; then
      mkdir ~/.ssh
    fi
    ssh-keygen -mPEM -f ~/.ssh/id_rsa -N "" 
  fi

  if [[ "${prompt_name:-}" ]]; then
    echo "$prompt_name" >/tmp/prompt_name
  fi

  cd /work || return 1
  local modules=( $(find -L /work -mindepth 1 -maxdepth 1 -type d -not -name '.*') ) || return 1 
  if (( ${#modules[*]} == 0 )); then
    source /etc/profile.d/shell-start-0.sh || return 1
    cell plant || return 1
  fi

  if [[ "${COMMAND:-}" ]]; then
    /bin/bash -lc "$COMMAND"
  else
    /bin/bash -l
  fi

}

main

