#!/usr/bin/env bash

main() {

  set -u

  if [[ ! "${USER:-}" ]]; then
    echo "You must set env var USER to your user name" >&2
    return 1
  fi

  if [[ ! -f ~/.ssh/id_rsa ]]; then
    if [[ ! -d ~/.ssh ]]; then
      mkdir ~/.ssh
    fi
    ssh-keygen -mPEM -f ~/.ssh/id_rsa -N "" 
  fi

  if [[ "${prompt_name:-}" ]]; then
    echo "$prompt_name" >/tmp/prompt_name
  fi

  local shell_start_files=( $(find /repo -mindepth 2 -maxdepth 2 -type f -name "shell-start*") )
  local shell_start_file
  for shell_start_file in ${shell_start_files[*]}; do
    ln -sf $shell_start_file /etc/profile.d/ || return 1
  done

  local bin_folders=( $(find /repo -mindepth 2 -maxdepth 2 -type d -name bin) )
  local bin_folder
  for bin_folder in ${bin_folders[*]}; do
    ln -sf $bin_folder/* /usr/bin/ || return 1
  done

  cd /work || return 1
  local modules=( $(find -L /work -mindepth 1 -maxdepth 1 -type d -not -name '.*') ) || return 1 
  if (( ${#modules[*]} == 0 )); then
    source /etc/profile.d/shell-start-0.sh || return 1
    export SIMPLETON_LIB=$SIMPLETON_REPO/lib
    cell plant || echo "Failed to plant cells." >&2
  fi

  if [[ "${COMMAND:-}" ]]; then
    /bin/bash -lc "$COMMAND"
  else
    /bin/bash -l
  fi

}

main

