#!/usr/bin/env bash

##########################################################
# BASH-LIFTED
# A bash library of functions to increase debugability of bash scripts.
##########################################################

type -t bash_lifted_init >/dev/null && return 0

declare -A trace_var_old trace_var_sub
debug_id_current=0

# this is empty, meaning we haven't forked yet. the top level process having a blank id
fork_id_current=    

fork_debug_id=0

# Run this near the top of scripts using this functionality, after the commandline parameters 
#   have been processed
bash_lifted_init() {
  autorepair_level=${autorepair_level:-${repair:-1}}
}

reply_to_caller() {
  if [[ "${reply_file:-}" ]]; then
    echo "$*" >>$reply_file || return 1
  fi
  return 0
}

reached_debug_id() {
  local r1 r2 p1 p2 i=0
  OIFS=$IFS
  IFS=. r1=( $fork_debug_id ) r2=( $1 )
  IFS=$OIFS
  while true; do
    p1=${r1[$i]:-} p2=${r2[$i]:-}
    (( i++ ))
    if [[ "$p1" ]]; then
      if [[ "$p2" ]]; then
        if (( p1 < p2 )); then
          return 1
        elif (( p1 > p2 )); then
          return 0
        fi
      else
        return 0
      fi
    else
      if [[ "$p2" ]]; then
        return 1
      else
        return 0
      fi
    fi
  done
}

