#!/usr/bin/env bash

##########################################################
# BASH-LIFTED
# A bash library of functions to increase debugability of bash scripts.
##########################################################

type -t bash_lifted_init >/dev/null && return 0

declare -A trace_var_old trace_var_sub
debug_id_current=0

# this is empty, meaning we haven't forked yet. the top level process having a blank id
fork_id_current=    

fork_debug_id=0

# Run this near the top of scripts using this functionality, after the commandline parameters 
#   have been processed
bash_lifted_init() {
  autorepair_level=${autorepair_level:-${repair:-1}}
}

