#!/bin/bash

type -t bash_lib_loaded >/dev/null && return 0
bash_lib_loaded=t

set -u +Hm -o pipefail
shopt -s expand_aliases extglob dotglob globstar huponexit

umask 0077  # to make created files readable only by the user by default

if [[ ! -v fd_original_in ]]; then
  exec {fd_original_in}<&0
  exec {fd_original_out}>&1
  exec {fd_original_err}>&2
  exec {fd_original_trace}>&${fd_trace:-2}
fi

# use this to make vars local which are computed by another function call
alias local_vars='[[ "${to_local_vars:-}" ]] && eval "local $to_local_vars"'

# some parts of bash require a statement, but in some cases there's nothing to be
# done, so this serves as a clear indication that nothing needs to be done, and yet
# satisfies the requirement that a statement be there. 
alias nothing=':;'

# some required defaults
export tmp_folder="${tmp_folder:-/tmp}"
export EDITOR=${EDITOR:-vim}

export tracing_depth=${tracing_depth:-0}
export no_trace_depth=${no_trace_depth:-0}

alias start_tracing='(( tracing_depth++ == 0 )) && set -x'
alias stop_tracing='(( --tracing_depth <= 0 )) && { set +x; tracing_depth=0; }'

# used in if condition to be more clear.
# instead of:
#   if ! diff $f1 $f2; then ...
# write:
#   if are_different $f1 $f2; then ...
alias files_are_different='! diff'
alias files_are_same='diff'

NL=$'\n'
CR=$'\r'
TAB=$'\t'
ESC=$'\e'
DQ='"'
SQ="'"

     DIM_RED=$'\033[0;31m'
         RED=$'\033[1;31m'
   DIM_GREEN=$'\033[0;32m'
       GREEN=$'\033[1;32m'
  DIM_YELLOW=$'\033[0;33m'
      YELLOW=$'\033[1;33m'
    DIM_BLUE=$'\033[0;34m'
        BLUE=$'\033[1;34m'
  DIM_PURPLE=$'\033[0;35m'
      PURPLE=$'\033[1;35m'
    DIM_CYAN=$'\033[0;36m'
        CYAN=$'\033[1;36m'
   DIM_WHITE=$'\033[0;37m'
       WHITE=$'\033[1;37m'
   DIM_BLACK=$'\033[0;38m'
       BLACK=$'\033[1;38m'
       RESET=$'\033[0m'
  CLEAR_LINE=$'\033[2K\r'
       CLEAR=$'\033[2J'
CLEAR_SCREEN=$'\033[2J\r\033[H'
   CURSOR_UP=$'\033[1A'
     REVERSE=$'\033[7m'
   HIGHLIGHT=$'\033[1;37m'

COL0=$'\n\e[A\e[0G'     COL5=$'\n\e[A\e[5G'     COL10=$'\n\e[A\e[10G'
COL15=$'\n\e[A\e[15G'   COL20=$'\n\e[A\e[20G'   COL25=$'\n\e[A\e[25G'
COL30=$'\n\e[A\e[30G'   COL35=$'\n\e[A\e[35G'   COL40=$'\n\e[A\e[40G'
COL45=$'\n\e[A\e[45G'   COL50=$'\n\e[A\e[50G'   COL55=$'\n\e[A\e[55G'
COL60=$'\n\e[A\e[60G'   COL65=$'\n\e[A\e[65G'   COL70=$'\n\e[A\e[70G'
COL75=$'\n\e[A\e[75G'   COL80=$'\n\e[A\e[80G'   COL85=$'\n\e[A\e[85G'
COL90=$'\n\e[A\e[90G'   COL95=$'\n\e[A\e[95G'   COL100=$'\n\e[A\e[100G'
COL110=$'\n\e[A\e[110G' COL120=$'\n\e[A\e[120G' COL130=$'\n\e[A\e[130G'
COL140=$'\n\e[A\e[140G' COL150=$'\n\e[A\e[150G' COL160=$'\n\e[A\e[160G'
COL170=$'\n\e[A\e[170G' COL180=$'\n\e[A\e[180G' COL190=$'\n\e[A\e[190G'
COL200=$'\n\e[A\e[200G'

eval "printf -v hbar_tilde '%.s~' {1..${COLUMNS:-40}}"
eval "printf -v hbar_equals '%.s=' {1..${COLUMNS:-40}}"
eval "printf -v hbar_minus '%.s-' {1..${COLUMNS:-40}}"

get_var_value() {
  local var_name=$1 val_name=${2:-value}
  if [[ "$var_name" =~ ^[0-9]+ ]]; then
    eval "$val_name=\$$var_name"
  else
    local -n _var=$var_name _val=${2:-value} || return 1
    _val='(unbound)'
    if is_array _var; then
      if [[ "${_var:-}" ]] && (( ${#_var[*]} > 20 )); then
        _val="( ${_var[*]:0:20} ... )"
      else
        _val="( ${_var[*]:-} )"
      fi
    elif is_set _var; then
      local c=0 k v
      _val="( "
      for k in "${!_var[@]}"; do
        v=${_var[$k]}
        if [[ "${v:-}" ]]; then
          _val+="$k=$v "
        else
          _val+="$k=(empty) "
        fi
        (( c++ ))
        if (( c > 20 )); then
          _val+="... "
          break
        fi
      done
      _val+=")"
    elif [[ -v _var ]]; then
      _val=$_var
      newlines=preserved quotes=single shell_quote_var _val
    else
      _val='(unset)'
    fi
  fi
}

micros_to_minute() {
  local -n _t=$1
  (( _t = _t / 1000000 / 60 ))
}

# input:
#   $1   path to file with wildcard in it
# output:
#   returns true (0) if at least one file exists matching the pattern
wild_file_exists() {
  local pattern=$1
  [[ "$pattern" != *'*'* ]]
}

progress_bar_start() {
  local new_progress_bar_size=$1 front_load=${front_load:-3} below_log=${below_log:-verbose}
  if ! log_level_at_least $below_log && [[ "${trace_structure:-f}" == f ]]; then
    progress_bar_total=${progress_bar_total:-0}
    progress_bar_nesting=${progress_bar_nesting:-0}
    progress_bar_front_load=${progress_bar_front_load:-$front_load}
    (( progress_bar_total += new_progress_bar_size ))
    (( progress_bar_nesting++ ))
    progress_bar_start_time=${progress_bar_start_time:-${EPOCHREALTIME/./}}
    progress_bar_current=0
    
    if (( progress_bar_total > 2 )); then
      echo -n "0% complete" >&$fd_original_err
#    else
#      echo -n "..." >&$fd_original_err
    fi
  fi
}

progress_bar_next() {
  local amount_to_add=${1:-1} percentage
  if (( ${progress_bar_nesting:-0} > 0 )); then
    (( progress_bar_current += amount_to_add ))
    if (( progress_bar_total > 2 )); then
      (( percentage = 100 * progress_bar_current / progress_bar_total ))
      local time_taken_micro total_micro remaining_micro extra= remaining_min current_time=${EPOCHREALTIME/./}
      (( time_taken_micro = current_time - progress_bar_start_time ))
      (( total_micro = time_taken_micro * progress_bar_total / progress_bar_current ))
      (( remaining_micro = total_micro - time_taken_micro ))

      remaining_min=$remaining_micro
      (( percentage < 25 )) && (( remaining_min *= progress_bar_front_load ))
      micros_to_minute remaining_min
      if (( remaining_min > 0 )); then
        extra=" ($remaining_min minute(s) left)"
      fi

      if [[ "${progress_bar_last_percentage:-}" != $percentage ]]; then
        echo -n "$CLEAR_LINE" >&$fd_original_err
        echo -n "...$percentage% complete$extra" >&$fd_original_err
      fi
      progress_bar_last_percentage=$percentage
    else # too few total items in progress bar to show %
      local out
      eval "printf -v out '%.s.' {1..$amount_to_add}"
      echo -n "$out"
    fi
  fi
}

progress_bar_nudge() {
  local output_char=${1:-.}
  if (( ${progress_bar_nesting:-0} > 0 )); then
    echo -n "$output_char" >&$fd_original_err
  fi
}

progress_bar_stop() {
  if (( ${progress_bar_nesting:-0} > 0 )); then
    (( progress_bar_nesting-- ))
    if (( progress_bar_nesting == 0 )); then
      local time_taken current_time=${EPOCHREALTIME/./}
      (( time_taken = current_time - progress_bar_start_time ))
      micros_to_minute time_taken
      if (( time_taken > 0 )); then
        echo "...Completed in $time_taken minutes." >&$fd_original_err
      else
        echo -n "${CLEAR_LINE}" >&$fd_original_err
      fi
      unset progress_bar_total progress_bar_nesting \
            progress_bar_front_load progress_bar_start_time \
            progress_bar_current
    fi
  fi
}

# input:
#   $1   previous timestamp (in microseconds, as from EPOCHREALTIME
#   $2   next timestamp
#   $3   var name to write result to, writes time in seconds with .
micro_time_diff() {
  local before=$1 after=$2
  local -n to_var=$3
  local diff=$((after-before)) p1 p2
  diff="000000$diff"
  p1=${diff%%??????}
  p2=${diff#$p1}
  p1=${p1##*(0)}
  to_var="${p1:-0}.$p2"
}

remove_empty_parents() {
  local dir=$1 contents recursive=${recursive:-f}
  contents=( $(find1 "$dir") ) || return 1
  if (( ${#contents[*]} == 0 )); then
    rm -r $dir || return 1
    if [[ $recursive == t && "$dir" == /*/* ]]; then
      remove_empty_parents "${dir%/*}" || return 1
    fi
  fi
}

valid_var_name() { 
  [[ "$1" =~ [a-zA-Z0-9_]+ ]]
}

# used for temporary logging to debug issues. Uses of this should be removed before
#   committing changes. 
zombie() {
  local s=${BASH_SOURCE[1]:-(no source)} \
    f=${FUNCNAME[1]:-(no func)}
  s=${s##*/}
  echo "$CYAN$EPOCHREALTIME debug_id=${fork_debug_id:-} $f $s:${BASH_LINENO[0]} $*$RESET" >&$fd_original_err
}

zombie_lap_reset() {
  zombie_lap_total=0
  unset zombie_lap_time
  declare -Ag zombie_lap_time
  unset zombie_lap_count
  declare -Ag zombie_lap_count
}

# used for temporary debugging of performance issues
# will aggregate time spent between each lap and show percentages and totals
# calls to this should be removed before committing code
# usage: zombie_lap "message..."
zombie_lap() {
  local current=$* ts=${EPOCHREALTIME/./} diff=0 p p1 p2 m

  if [[ "${zombie_lap_prev:-}" ]]; then
    m="$zombie_lap_prev -> $current"
  else
    m=$current
  fi
  zombie_lap_prev=$current

  if [[ "${zombie_lap_last_ts:-}" ]]; then
    (( diff = ts - zombie_lap_last_ts ))
  else
    zombie_lap_reset
  fi

  zombie_lap_last_ts=$ts
  : ${zombie_lap_time[$m]:=0} ${zombie_lap_count[$m]:=0} \
    ${zombie_lap_detail:=f} ${zombie_lap_max_diff:=10000000}
  local extra=

  if (( diff > 0 )); then
    if (( diff < $zombie_lap_max_diff )); then
      (( zombie_lap_time[$m] += diff ))
      (( zombie_lap_count[$m] += 1 ))
      (( zombie_lap_total += diff ))
      if [[ $zombie_lap_detail == f ]]; then
        return 0
      fi
      (( percent = zombie_lap_time[$m] * 10000 / zombie_lap_total ))
      percent="00$percent"
      p1=${percent%??}
      p2=${percent#$p1}
      p1=${p1##*(0)}
      percent="${p1:-0}.$p2"
      extra="[diff=$diff sum=${zombie_lap_time[$m]} $percent%] "
    else
      extra="[exceeded zombie_lap_max_diff $diff > $zombie_lap_max_diff] "
    fi
  fi

  if [[ $zombie_lap_detail == t ]]; then
    echo "$CYAN$EPOCHREALTIME zombie_lap: $extra$m$RESET" >&2
  fi
}

zombie_lap_summary() {
  local key val count percent p1 p2
  echo "TIME${TAB}PERCENT${TAB}COUNT${TAB}NAME" >&2
  for key in "${!zombie_lap_time[@]}"; do
    val=${zombie_lap_time[$key]}
    count=${zombie_lap_count[$key]}
    if [[ "$val" && "$val" -gt 0 ]]; then
      (( percent = val * 10000 / zombie_lap_total ))
      percent="00$percent"
      p1=${percent%??}
      p2=${percent#$p1}
      p1=${p1##*(0)}
      percent="${p1:-0}.$p2"
      echo "$val$TAB$percent%$TAB$count$TAB$key"
    fi
  done | sort -gr >&2
  echo "Total: $zombie_lap_total" >&2
}

# calls to this should be converted to normal evals before committing code
zombie_eval() {
  local s=${BASH_SOURCE[1]:-(no func)}
  s=${s##*/}
  echo "$CYAN$EPOCHREALTIME $s:${BASH_LINENO[0]} $*$RESET" >&2
  eval "$*"
}

array_contains() {
  local -n __array=$1
  local look_for=$2 i found=f
  for (( i = 0; i < ${#__array[*]}; i++ )); do
    if [[ ${__array[$i]} == "$look_for" ]]; then
      found=t
      break
    fi
  done
  [[ $found == t ]]
}

dedup_array() {
  local -n from=$1 to=$2
  local -A already_copied
  local e
  for e in "${from[@]}"; do
    if [[ ! "${already_copied[$e]:-}" ]]; then
      to+=( "$e" )
      already_copied["$e"]=1
    fi
  done
}

sort_array() {
  local -n _v=$1
  local v OIFS=$IFS
  IFS=$NL
  _v=( $(
  for v in "${_v[@]}"; do
    echo "$v"
  done | sort) )
  IFS=$OIFS
}

intersect() {
  local -n _old_values=$1 _new_values=$2 _intersected=$3
  local v
  for v in "${!_old_values[@]}"; do
    if [[ -v _new_values[$v] ]]; then
      _intersected[$v]=1
    fi
  done
  debug_return_vars=$3
}

clear_set() {
  local -n _x=$1
  local v
  for v in "${!_x[@]}"; do
    unset _x[$v]
  done
}

# will NOT wipe out what's already in target var
add_to_set() {
  local -n _from=$1 _to=$2
  local v
  for v in "${!_from[@]}"; do
    _to[$v]=1
  done
  debug_return_vars=$2
}

# will NOT wipe out what's already in target var
add_to_map() {
  local -n _from=$1 _to=$2
  local v
  for v in "${!_from[@]}"; do
    _to[$v]=${_from[$v]}
  done
  debug_return_vars=$2
}

# inputs:
#   $1   name of variable containing string to add
#   $2   name of variable to add string to
add_to_string_if_missing() {
  local -n element=$1 target_string=$2
  if [[ ! -v target_string ]]; then
    target_string=
  fi
  if [[ " $target_string " != *" $element "* ]]; then
    if [[ "${target_string:-}" ]]; then
      target_string+=" $element"
    else
      target_string+="$element"
    fi
  fi
  debug_return_vars=$2
}

# variable should be checked to see if it is set first
is_array() {
  local -n _array=$1
  local rc
  set +u
  [[ ${_array@a} == a ]]; rc=$?
  set -u
  return $rc
}

# variable should be checked to see if it is set first
is_set() {
  local -n _set=$1
  local rc
  set +u
  [[ ${_set@a} == A ]]; rc=$?
  set -u
  return $rc
}

split_to_array() {
  local -n from_var=$1;
  local -n to_var=${2:-$1}
  local separator=${separator:-$'\n'}
  local IFS=$separator
  to_var=( $from_var )
}

array_to_string() {
  local -n _from_array=$1 _to_string=$2
  local v
  _to_string="( "
  for v in "${_from_array[@]}"; do
    quotes=single shell_quote_var v
    _to_string+="$v "
  done
  _to_string+=")"
}

string_to_array() {
  local -n _from_string=$1 _to_array=$2
  local from=$_from_string part
  local separator=${separator:-${sep:-' '}}
  _to_array=()
  while [[ "$from" == *"$separator"* ]]; do
    part=${from%%$separator*}
    _to_array+=( "$part" )
    from=${from#$part$separator}
  done
  if [[ "$from" ]]; then
    _to_array+=( "$from" )
  fi
}

string_to_set() {
  local -n _from_string=$1 _to_set=$2
  local v
  for v in ${_from_string}; do
    _to_set[$v]=1
  done
  debug_return_vars=$2
}

# WILL wipe out target var, and replace with source
copy_set() {
  clear_set $2
  add_to_set $1 $2
}

# WILL wipe out target var, and replace with source
copy_map() {
  clear_set $2
  add_to_map $1 $2
}

# inputs:
#   $1   var name which is a set (associative array) to read from
#   $2   var name which is an array to write the keys of the set to
keys_to_array() {
  local -n key_set=$1 out_array=$2
  if [[ -v key_set[*] ]]; then
    if (( ${#key_set[*]} > 0 )); then
      out_array=( "${!key_set[@]}" )
    fi
  else
    out_array=()
  fi
  debug_return_vars=$2
}

get_value_from_table() {
  local -n data=${table_var}_data fields=${table_var}_fields
  local field=$field row=${row:-0} offset i field_count=${#fields[*]} data_count=${#data[*]}

  value=
  (( offset = field_count * row ))
  for (( i = 0; i < field_count; i++ )); do
    if [[ ${fields[$i]} == $field ]]; then
      value=${data[$(( offset + i ))]}
      break
    fi
  done
}

# get input from the user to select from a given set of possibilities and assign
# the result to the given variable.
# usage: choose {prompt string} {var} {choices...}
# prompt string: prompt to show user
# var: variable to assign choice to
# choices: space separated list of options
choose() {
  local prompt=$1; shift
  local var_name=$1; shift
  local -n var=$var_name
  
  if (( $# > 0 )); then
    local PS3=$prompt
    select var; do break; done
    if [[ "$var" ]]; then
      return 0
    else
      return 1
    fi
  else
    if [[ "${secret_vars:-}" && " $secret_vars " == *\ $var_name\ * ]]; then
      read -sr -p "$prompt" $var_name >&2 || return 1
      echo "********" >&2
    else
      read -r -p "$prompt" $var_name >&2 || return 1
    fi
  fi
  return 0
}

out_wrap() {
  local message="$@" indent=${indent:-0} pad
  trim_ws message
  message=${message//$NL/}
  message=${message//+( )/ }
  printf -v pad %${indent}s
  echo "$message" | fold -s -w $((COLUMNS-1)) | sed "s/^/$pad/"
}

# primitive logging functions. If using omni-logger, you should use log_info, etc instead
out() {
  local indent=${indent:-0} pad
  printf -v pad %${indent}s
  echo "$@" | sed "s/^/$pad/"
}

# primitive logging functions. If using omni-logger, you should use log_info, etc instead
out_no_nl() {
  local message="$*" indent=${indent:-0} pad
  printf -v pad %${indent}s
  echo -n "$message" | sed "s/^/$pad/"
}

# primitive logging functions. If using omni-logger, you should use log_fatal, etc instead
err() {
  #echo "$RED$*$RESET" >&2
  echo "$*" >&$fd_original_err
}

# primitive logging functions. If using omni-logger, you should use log_warn, etc instead
warn() {
  echo "$YELLOW$*$RESET" >&2
}

# indents an input stream by the given number of spaces (defaults to 2 spaces)
indent() {
  local amount=${1:-2} pad
  printf -v pad %${amount}s
  sed "s/^/$pad/"
}

function_exists() {
  declare -pf $1 &>/dev/null
}

execute_if_exists() {
  local function_name=$1 full_command=$*
  if declare -pf $function_name &>/dev/null; then
    $full_command || return 1
  fi
  return 0
}

ansi_filter_stream() {
  local line
  local IFS=
  while read -r line || [[ "$line" ]]; do
    printf '%s\n' "${line//$ESC[\[(]*([0-9;])[@-n]/}"
  done
}

ansi_filter_var() {
  local -n var=$1
  var="${var//$ESC[\[(]*([0-9;])[@-n]/}"
  var="${var//$ESC[?????l/}"
}

plural() {
  local count=$1 word=$2
  if [[ $count -eq 1 ]]; then
    echo "$count $word"
  else
    echo "$count ${word}s"
  fi
}

find1() {
  if [[ ! -d "${1:-}" ]]; then
    echo "find1: directory missing: ${1:-}" >&$fd_original_err
    return 1
  fi
  local path=$1; shift
  find -L "$path" -mindepth 1 -maxdepth 1 "$@"
  return 0
}

hydrate_template() {
  if [[ "$line" =~ \$ ]]; then
    line="${line//\"/\\\"}"
    eval "echo \"$line\"" || return 1
  else
    echo "$line"
  fi
}

# prompt_ynsq {message} {var to save result into}
# Allows: (y)es (n)o (q)uit
prompt_ynq() {
  local message=$1 var=$2
  if [[ ${tracing_midline:-f} == t ]]; then
    tracing_midline=f
    echo >&2
  fi

  while true; do
    read -s -n 1 -p "${GREEN:-}$message${RESET:-} (y/n/q) " $var >&2
    case ${!var} in
      y)
        echo "Yes" >&2  
        ;;
      n)
        echo "No" >&2 
        ;;
      q)
        echo "Quit" >&2 
        ;;
      *)
        err "Pick one of: (y)es (n)o (q)uit"
        continue
        ;;
    esac
    break
  done
}

# should pass in a single command or a { } block of commands
# will run this command after script terminates (whether successfully or in error)
defer() {
  if [[ "${cleanup_on_exit:-}" != *"$1"* ]]; then
    eval "cleanup_on_exit+='$1 &>/dev/null;'"
  fi
}

undefer() {
  local command=$1
  cleanup_on_exit=${cleanup_on_exit/"$command &>/dev/null;"/}
  eval "$command"
}

# usage: random {p=number of possibilities}
#   sets r={random number between 0 and p-1}
#   it will be fairly evenly distributed below about 1000, but will become more biased as it gets higher
random() {
  local p=$1
  r=$((RANDOM % p))
}

# usage: random_sleep {min} {max}
#   will sleep for a random interval between min and max
random_sleep() {
  local min=$1; shift
  local max=$1
  random $((max-min))
  sleep $((min+r))
}

escape_regex_single() {
  local -n internal_var=$1
  internal_var=${internal_var//\"/\\\"}
  internal_var=${internal_var// /\\ }
  internal_var=${internal_var//\(/\\\(}
  internal_var=${internal_var//)/\\)}
  internal_var=${internal_var//\?/\\\?}
  internal_var=${internal_var//\$/\\\$}
}

escape_regex() {
  local -n var=$1
  local trim=${trim:-f} var_array

  if [[ $trim == t ]]; then
    var_array=$var
    var=
    split_to_array var_array
    local i e size=${#var_array[*]}
    for (( i = 0; i < size; i++ )); do
      e=${var_array[$i]}
      e=${e##*( )}
      e=${e%%*( )}
      escape_regex_single e
      var+=$e
      if (( i < size - 1 )); then
        var+=$NL
      fi
    done
  else
    escape_regex_single var
  fi
}

literal_to_regex() {
  local -n var=$1
  var=${var//\\/\\\\}
  var=${var//\$/\\\$}
  var=${var//^/\\^}
  var=${var//\[/\\\[}
  var=${var//\]/\\\]}
  var=${var//./\\.}
}

shell_quote_var() {
  local var_name=$1
  local -n var=$var_name
  local quotes=${quotes:-single} # can be single, double, or dollar
  local newlines=${newlines:-preserved} # can be escaped or preserved
  local quote_empty=${quote_empty:-t}

  if [[ ! -v var ]]; then
    log_fatal "shell_quote_var called on unset var: $1"
    return 1
  fi

  if [[ "$var" =~ \<|\>|\(|\)|\"|\'|\\|\ |\$|$NL ]]; then
    if [[ $quotes == single ]]; then
      var=${var//\'/\'\"\'\"\'}
      var="'$var'"
    elif [[ $quotes == dollar ]]; then
      var=${var//\'/\\x27}
      var=${var//$NL/\\n}
      var="\$'$var'"
    else
      var=${var//\\/\\\\}
      var=${var//\"/\\\"}
      var=${var//\$/\\\$}
      var="$DQ$var$DQ"
    fi
  elif [[ ! "$var" && $quote_empty == t ]]; then
    if [[ $quotes == single ]]; then
      var="''"
    elif [[ $quotes == dollar ]]; then
      var="\$''"
    else
      var='""'
    fi
  fi

  if [[ "$newlines" == escaped ]]; then
    var=${var//$NL/\\n}
  fi

  return 0
}

dir_is_empty() {
  local content=( "$1"/* )
  [[ ! -e $content ]]
}

# will remove duplicate whitespace and trim leading and trailing
# do not use for large strings, it is too inefficient
compress_ws() {
  local -n v=$1
  v=${v//+([ $NL$TAB])/ }
  v=${v##*([ $NL$TAB])}
  v=${v%%*([ $NL$TAB])}
}

# usage: trim_ws {var name}
# will remove trailing and leading whitespace
trim_ws() {
  local -n x=$1
  if (( ${#x} > 1000 )); then
    x=$(echo -n "$x" | awk '
      BEGIN { after_first_line = 1 }
      NR == 1 { sub("^ +", "") }
      after_first_line == 1 { print line }
      { line = $0 }
      END { sub(" +$", "", line); if (NR > 0) print line }')
  else
    x=${x##*([$NL $TAB])}
    x=${x%%*([$NL $TAB])}
  fi
}

# usage: echo -e "\n\n blah  \n\n" | trim_stream_nl
# will trim empty lines from beginning and end of given string
# will leave exactly one trailing newline at the end
trim_stream_nl() {
  local block
  read -r -d '' block
  block=${block##*($NL)}
  block=${block%%*($NL)}
  echo "$block"
}

# usage: echo " blah   " | trim
# will trim whitespace from beginning and end of each line in the given input
trim_stream() {
  sed -E -e 's/^[[:space:]]+//' -e 's/[[:space:]]+$//' | grep -v '^$'
}

declare -A apad_size apad_min apad_max
# append a string to another string + padding according to the class of item being added
# Usage: apad {base var name} [{class of append string} {append string}]...
# The base var will be directly appended to with the append string and maybe padding
# You should include spaces in the append string itself if you want to guarantee a minimum
#   amount of space.
# You may define explicit min/maxes for various classes by adding entries to the apad_min and
#   apad_max maps, and can setup initial sizes with the apad_size map
apad() {
  local -n base=$1; shift
  local class append append_size class_size class_min class_max pad pad_size
  while (( $# > 1 )); do

    class=$1 append=$2; shift 2
    append_size=${#append}

    if [[ ! -v apad_min[$class] ]]; then
      apad_min[$class]=0
    fi
    class_min=${apad_min[$class]}

    if [[ ! -v apad_size[$class] ]]; then
      apad_size[$class]=$class_min
    fi
    class_size=${apad_size[$class]}

    if [[ ! -v apad_max[$class] ]]; then
      apad_max[$class]=1000
    fi
    class_max=${apad_max[$class]} 

    if (( append_size > class_size && class_size < class_max )); then
      apad_size[$class]=$append_size
      if (( class_size > class_max )); then
        apad_size[$class]=$class_max
      fi
    fi

    pad_size=0
    if (( class_size > append_size )); then
      (( pad_size = class_size - append_size ))
    fi

    base+=$append

    if (( pad_size > 0 )); then
      printf -v pad %${pad_size}s
      base+=$pad
    fi

  done
}

# Usage: apad_calc [{class of append string} {append string}]...
# similar to apad, except that it doesn't write to a var, it only calculates boundaries
apad_calc() {
  local class append append_size class_size class_min class_max pad pad_size
  while (( $# > 1 )); do

    class=$1 append=$2; shift 2
    append_size=${#append}

    if [[ ! -v apad_min[$class] ]]; then
      apad_min[$class]=0
    fi
    class_min=${apad_min[$class]}

    if [[ ! -v apad_size[$class] ]]; then
      apad_size[$class]=$class_min
    fi
    class_size=${apad_size[$class]}

    if [[ ! -v apad_max[$class] ]]; then
      apad_max[$class]=1000
    fi
    class_max=${apad_max[$class]} 

    if (( append_size > class_size && class_size < class_max )); then
      apad_size[$class]=$append_size
      if (( class_size > class_max )); then
        apad_size[$class]=$class_max
      fi
    fi

  done
}

# For debugging: shows the current apad padding information
apad_info() {
  local k
  for k in "${!apad_size[@]}"; do
    echo "$k: size=${apad_size[$k]} min=${apad_min[$k]} max=${apad_max[$k]}"
  done
}

upper_first_char() {
  local string=$1
  local first=${string:0:1}
  first=$(echo -n "$first" | tr '[:lower:]' '[:upper:]')
  echo -n "$first${string:1}"
}

# usage: convert_to_seconds {from time period} {to var name}
convert_to_seconds() {
  local from=$1
  local -n _to=$2
  case "$from" in
    *s)
      _to=${from%s}
    ;;
    *m)
      _to=$((${from%m}*60))
    ;;
    *h)
      _to=$((${from%h}*60*60))
    ;;
    *d)
      _to=$((${from%d}*24*60*60))
    ;;
    *w)
      _to=$((${from%w}*7*24*60*60))
    ;;
    *y)
      _to=$((${from%y}*365*24*60*60))
    ;;
    *)
      if [[ "$from" =~ ^[0-9]+$ ]]; then
        # default to seconds
        _to=$from
      else
        log_fatal "Unknown time format, use something like: 4h, 3d, 5m"
        return 1
      fi
    ;;
  esac
  return 0
}

# usage: convert_to_seconds {from seconds} {to var name}
convert_from_seconds() {
  local from=$1
  local -n _to=$2
  if (( from < 120 )); then
    _to=${from}s
  elif (( from < 120 * 60 )); then
    _to=$(( from / 60 ))m
  elif (( from < 48 * 60 * 60 )); then
    _to=$(( from / 60 / 60 ))h
  else
    _to=$(( from / 60 / 60 / 24 ))d
  fi
}

get_overlap() {
  local i
  result=
  for ((i=0; i<${#1}; i++)); do
    [[ "${1:$i:1}" != "${2:$i:1}" ]] && break
    result+=${1:$i:1}
  done
}

# inputs: 
#   from    directory to link to target
#   to      target to link to
#   timeout how long to wait in miliseconds
# if timeout is not given, then attempt will immediately fail if it can not get the lock right away
#   otherwise it will keep trying until the timeout is reached or the lock is obtained.
link_lock() {
  local from=$from
  local to=$to
  local timeout=${timeout:-}
  local pid_file=${pid_file:-$to/pid}

  local log_vars='from to timeout'
  begin_function_hi

    if [[ ! -e "$from" ]]; then
      log_fatal "$from doesn't exist, can't link lock it"
      fail1
    fi
    
    if [[ -L "$to" ]]; then

      log_debug "Lock link exists already: $to"
      local pid=

      if [[ -f "$pid_file" ]]; then
        pid=$(<"$pid_file")
        if [[ "$pid" == $$ ]]; then
          log_debug "This process already owns the lock, so we are done."
          abort
        fi
      fi

      # check to see if the process is still running
      if [[ ! "$pid" ]] || ! ps $pid &>/dev/null; then
        rm "$to" || fail
        log_debug "Removed stale lock: $to with pid: $pid"
      fi

    elif [[ -e "$to" ]]; then
      log_fatal "$to already exists and it's not a link. Can't obtain lock."
      fail1
    fi

    local parent=${to%/*}
    if [[ ! -d "$parent" ]]; then
      log_fatal "Target of link lock isn't in a folder ($to)"
      fail1
    fi

    local timeleft
    let timeleft=timeout
    local delay=250
    local success=f
    begin_while true; doo
      ln -sn "$from" "$to" &>/dev/null && success=t
      if [[ $success == t ]]; then
        echo $$ >"$pid_file" || fail
        break
      fi

      if [ ! "$timeout" ]; then
        break
      fi

      local seconds_to_wait=$(dc -e "2 k $delay 1000 / p")
      log_debug "Failed to obtain lock. Waiting $seconds_to_wait seconds before trying again."
      sleep $seconds_to_wait
      timeleft=$((timeleft-delay))

      let delay*=2
      if (( delay > 10000 )); then
        delay=10000
      fi

      if (( timeleft <= 0 )); then
        log_warn "Timeout reached. Couldn't obtain the lock in time."
        break
      fi

    end_while

    if [[ $success == f ]]; then
      log_debug "Failed to obtain lock."
      fail1
    fi

    defer "rm '$pid_file' '$to' &>/dev/null"

    # lock obtained
    log_debug "Succeeded in obtaining lock."

  end_function
  handle_return
}

link_unlock() {
  local to=$to
  local pid_file=${pid_file:-$to/pid}

  if [[ -f "$pid_file" ]]; then
    rm "$pid_file" || return 1
  fi

  if [[ -L "$to" ]]; then
    rm "$to" || return 1
  elif [[ -e "$to" ]]; then
    log_fatal "$to is not a link, can't unlock it"
    return 1
  fi

  return 0
}

# inputs: folder_to_lock timeout pid_file
# if timeout is not given, then attempt will immediately fail if it can't get the lock right away
#   otherwise it will keep trying until the timeout is reached or the lock is obtained.
folder_lock() {
  local folder_to_lock=${folder_to_lock}
  local timeout=${timeout:-$lock_timeout}
  local pid_file=${pid_file:-$folder_to_lock/pid}
  local remove_folder_when_unlocked=${remove_folder_when_unlocked:-f}

  local log_vars='folder_to_lock timeout'
  begin_function_hi

    if [[ -d "$folder_to_lock" ]]; then

      log_debug "Lock folder exists already: $folder_to_lock"
      local pid=

      if [[ -f "$pid_file" ]]; then
        pid=$(<"$pid_file")
        if [[ "$pid" == $$ ]]; then
          log_debug "This process already owns the lock, so we are done."
          abort
        fi
      fi

      # check to see if the process is still running
      if [[ ! "$pid" ]] || ! ps $pid &>/dev/null; then
        rm -rf "$folder_to_lock" || fail
        log_debug "Removed stale lock: $folder_to_lock with pid: $pid"
      fi

    fi

    local timeleft
    let timeleft=timeout*1000
    local delay=250
    local success=f
    local parent=${folder_to_lock%/*}
    if [[ -d "$parent" ]]; then
      begin_while true; doo
        mkdir "$folder_to_lock" &>/dev/null && success=t
        if [[ $success == t ]]; then
          echo $$ >"$pid_file" || fail
          break
        fi

        if [ ! "$timeout" ]; then
          break
        fi

        local seconds_to_wait=$(dc -e "2 k $delay 1000 / p")
        log_debug "Failed to obtain lock. Waiting $seconds_to_wait seconds before trying again."
        sleep $seconds_to_wait
        timeleft=$((timeleft-delay))
        let delay*=2
        if [ "$timeleft" -le 0 ]; then
          log_warn "Timeout reached. Couldn't obtain the lock in time."
          break
        fi
      end_while
    else
      log_fatal "Attempting to obtain a folder lock when it's parent doesn't exist: $parent"
      fail1
    fi

    if [[ $success == f ]]; then
      log_debug "Failed to obtain lock."
      fail1
    fi

    if [[ $remove_folder_when_unlocked == t ]]; then
      defer "rm -r '$pid_file' '$folder_to_lock' &>/dev/null"
    fi

    log_debug "Succeeded in obtaining lock."

  end_function
  handle_return
}

folder_is_locked() {
  local folder_to_lock=$folder_to_lock
  local pid_file=${pid_file:-$folder_to_lock/pid}
  local is_locked=f
  if [[ -d "$folder_to_lock" ]]; then
    if [[ -f "$pid_file" ]]; then
      pid=$(<"$pid_file")
      if [[ "$pid" ]] && ps $pid &>/dev/null; then
        is_locked=t
      fi
    fi
  fi
  [[ "$is_locked" == t ]]
}

# inputs: folder_to_unlock pid_file
folder_unlock() {
  local folder_to_unlock=$folder_to_unlock
  local pid_file=${pid_file:-$folder_to_unlock/pid}
  local remove_folder_when_unlocked=${remove_folder_when_unlocked:-f}

  if [[ ! "$folder_to_unlock" ]]; then
    log_fatal "Usage: folder_to_unlock=... folder_unlock "
    return 1
  fi

  if [[ -d "$folder_to_unlock" && $remove_folder_when_unlocked == t ]]; then
    rm -r "$folder_to_unlock" || return 1
  fi

  if [[ -f "$pid_file" ]]; then
    rm "$pid_file" || return 1
  fi

  return 0
}

fd_read_lock() {
  local lock_path=$lock_path timeout=$timeout
  if [[ ! -d "${lock_path%/*}" ]]; then
    log_fatal "Bad lock path: $lock_path. It must either exist, or point to a file in a folder that exists."
    return 1
  fi
  if [[ ! -e "$lock_path" ]]; then
    touch "$lock_path" || return 1
  fi
  exec {lock_fd}<>$lock_path
  #zombie "Locking $lock_path write_lock=f timeout=$timeout fd=$lock_fd"
  flock -s -w $timeout $lock_fd || {
    log_fatal "Failed to get read lock for $lock_path within $timeout seconds"
    return 1
    }
}

fd_write_lock() {
  local lock_path=$lock_path timeout=$timeout
  if [[ ! -d "${lock_path%/*}" ]]; then
    log_fatal "Bad lock path: $lock_path. It must either exist, or point to a file in a folder that exists."
    return 1
  fi
  if [[ ! -e "$lock_path" ]]; then
    touch "$lock_path" || return 1
  fi
  exec {lock_fd}<>$lock_path
  flock -e -w $timeout $lock_fd || {
    log_fatal "Failed to get write lock for $lock_path within $timeout seconds"
    return 1
    }
}

fd_unlock() {
  flock -u $lock_fd
}

get_next_fd() {
  next_fd=$(ls -1 /proc/self/fd | tail -n1)
  let next_fd++
}

is_dir_empty() {
  eval "local contents=( $1/* )"
  local first=${contents[0]}
  [[ "${first%\*}" != "$first" ]]
}

pretend_filter=
case "${pretend:-}" in
  a|'')
    pretend=ask
  ;;
  f|t|ask)
  ;;
  *)
    pretend_filter=$pretend
    pretend=f
  ;;
esac

maybe() {
  local command_to_execute="$*"
  local execute

  case $pretend in
    f)
      execute=t
    ;;
    t)
      echo "Pretending: $command_to_execute" >&2
      execute=f
    ;;
    ask)
      local response
      echo "Will execute: $command_to_execute" >&2
      sleep 0.5
      read -p 'Are you sure? [yes/no/All/None/quit] ' -s -n1 response >&2
      case $response in
        y)
          echo "yes" >&2
          execute=t
        ;;
        A)
          echo "all" >&2
          pretend=f
          execute=t
        ;;
        N)
          echo "none" >&2
          pretend=t
          execute=f
        ;;
        q)
          echo "quit" >&2
          exit 1
        ;;
        *)
          echo "no" >&2
          execute=f
        ;;
      esac
    ;;
    *)
      log_fatal "Invalid pretend setting: $pretend. Must be one of: t f ask"
      return 1
    ;;
  esac

  if [[ $execute == t ]]; then
    log_info "Executing: $command_to_execute"
    eval "$command_to_execute" || return $?
  fi

  return 0
}

min() {
  result=$1
  if [[ $1 == inf || $2 -lt $1 ]]; then
    result=$2
  fi
}

max() {
  result=$1
  if [[ $2 == inf || $2 -gt $1 ]]; then
    result=$2
  fi
}

# input: $1 (name of array variable which was already populated 
#   with string values)
enum() {
  local i count array=$1 var
  eval "count=\${#$array[*]}"
  for ((i=0; i < count; i++)); do
    eval "var=\${$array[$i]}"
    eval "$var=$i"
  done
}

safe_link() {
  local from_all="$*" from to \
    force=${force:-f} \
    from_must_exist=${from_must_exist:-t} \
    ignore_existing=${ignore_existing:-f} \

  to=${from_all##* }
  from_all=${from_all% $to}

  local log_show_vars="^from_all ^to" log_vars="force from_must_exist"
  begin_function

    # log_debug "Linking $from_all to $to"

    if [[ "$to" == "$from_all" ]]; then
      log_fatal "Invalid parameters for safe_link: $*"
      fail1
    fi

    if [[ $to != */ ]]; then
      if [[ -L $to ]]; then
        rm "$to" || fail
      elif [[ -e $to ]]; then
        if [[ $ignore_existing == t ]]; then
          abort
        fi
        log_fatal "safe_link: target already exists: $to. If you want to make a link inside of this folder, make the target $to/ instead."
        fail1
      fi
    fi

    local files parent extra
    begin_for from in $from_all; doo

      if [[ "$from" == */\* || "$from" == *!* ]]; then
        extra= parent=${from%/*}
        if [[ "$from" == *!* ]]; then
          extra=${from##*/}
          extra=${extra#!}
          extra=${extra#(}
          extra=${extra%)}
          extra=" -not -name \"$extra\""
        fi
        files=$(find1 $parent -not -name ".*" $extra) || fail
        if [[ "$files" ]]; then
          safe_link $files $to || fail
        fi
        continue
      fi

      if [[ $from_must_exist == t && ! -e "$from" ]]; then
        log_fatal "Internal error: Source of link doesn't exist: $from"
        fail1
      fi

      local to_parent=${to%/*}
      local full_to=$to
      if [[ $to == */ ]]; then
        full_to+=${from##*/}
      fi

      if [[ ! -d "$to_parent" ]]; then
        log_fatal "Missing target folder for link: $to_parent"
      fi

      if [[ $force == t ]]; then
        ln -sfn "$from" "$full_to" || fail
      else
        if [[ -e "$full_to" ]]; then
          if [[ $ignore_existing ]]; then
            continue
          else
            log_fatal "Target of link operation already exists: $full_to"
            fail1
          fi
        fi
        ln -sn "$from" "$full_to" || fail
      fi

    end_for

  end_function
  debug_return_vars='from_all to'
  handle_return
}

# inputs:
#   $1               optional message to display at pause prompt
# outputs:
#   pause_response   contains key pressed (which is usually ignored)
pause() {
  if function_exists handle_user_interrupt; then
    handle_user_interrupt "Paused. "
  else
    local extra=
    if [[ "${fork_debug_id:-}" ]]; then
      extra=" at $fork_debug_id"
    fi
    echo >&$fd_original_err
    read -sp "$WHITE** PAUSED$extra ** ${1:-Press any key}$RESET" -n 1 pause_response >&$fd_original_err || true
    echo >&$fd_original_err
    echo >&$fd_original_err
  fi
}

# inputs:
#   $1               optional message to display at pause prompt
pause_qd() {
  local extra=
  if [[ "${fork_debug_id:-}" ]]; then
    extra=" at $fork_debug_id"
  fi
  local pause_response
  echo >&$fd_original_err
  read -sp "$WHITE** PAUSED$extra ** ${1:-} Press q to quit, D to debug here or any other key to continue.$RESET" -n 1 pause_response >&$fd_original_err || true
  echo >&$fd_original_err
  case $pause_response in 
    D)
      debug_stepping=t
      debug_start o
    ;;
    q)
      echo "Quitting..." >&$fd_original_err
      debug_exit=1 debugging=t
      if [[ "$reply_file" ]]; then
        echo "debugging=t" >$reply_file
      fi
      exit 1
    ;;
  esac
  echo >&$fd_original_err
  return 0
}

# resolves relative paths but does not resolve symlinks
# should run in a subprocess so dir change doesn't affect caller
# normal usage: x=$(unrealpath "$some_path")
unrealpath() {
  local p=$PWD x=$1
  shift
  local flags=$*
  if [[ "$x" != /* ]]; then
    x="$p/$x"
  fi
  realpath $flags "$x" || {
    log_fatal "Internal error: could not resolve $x"
    return 1 
    }
  return 0
}

# inputs: 
#   $1: var       name of var to add to
#   $2: add_value
# var will have trailing and leading spaces
add_word_to_string() {
  local var_name=$1 add_value=$2
  local -n var=$1
  if [[ -v var ]]; then
    if [[ "$var" != *" $add_value "* ]]; then
      var+="$add_value "
    fi
  else
    var=" $add_value "
  fi
}

# var must have trailing and leading spaces
remove_word_from_string() {
  local -n var=$1
  local remove_value=$2
  var=" $var "
  if [[ -v var && " $var " == *" $remove_value "* ]]; then
    local left=${var%%+( )$remove_value *} \
      right=${var##* $remove_value+( )}
    if [[ "$left" ]]; then
      if [[ "$right" ]]; then
        var="${left##+( )} ${right%%+( )}"
      else
        var="${left##+( )}"
      fi
    else
      if [[ "$right" ]]; then
        var="${right%%+( )}"
      else
        var=
      fi
    fi
  fi
}

# inputs:
#   $1    name of array
#   $2    element to remove
# will remove any elements that match, but those indexes will be removed also
remove_array_element() {
  local -n array=$1
  local element=$2 i
  for (( i = 0; i < ${#array[*]}; i++ )); do
    if [[ "${array[$i]}" == "$element" ]]; then
      unset array[$i]
    fi
  done
}

show_array() {
  local -n _array=$1
  local i size char_array=f

  set +u
  size=${#_array[*]}
  set -u

  echo "size=$size" >&$fd_original_err
  for i in "${!_array[@]}"; do
    if [[ ! -v _array[$i] ]]; then
      echo "$i: << MISSING >>" >&$fd_original_err
    else
      echo "$i: ${_array[$i]:-}" >&$fd_original_err
    fi
  done
}

rcp() {
  local shell="ssh"
  if [ "${port:-}" ]; then
      shell="ssh -p $port"
  fi
  RSYNC_RSH="$shell" rsync -a --append --inplace --partial --progress "$@"
}

# calculate the difference between two timestamps
# input: 
#   $1      start time
#   $2      end time
# output:
#   result  {end time} - {start time}
ts_diff() {
  local start=$1 end=$2
  result=$(dc -e "6k $end $start - p")
  #start=${start//./} end=${end//./}
  # (( result = end - start ))
  # local ipart=${result%??????}
  # result=${ipart}.${result#ipart}
}

debug_timer_start() {
  debug_counter_count=${debug_counter_count:-0}
  if (( debug_counter_count++ )); then nothing fi
  reply_to_caller "debug_counter_count=$debug_counter_count"
  debug_timer_start=$EPOCHREALTIME
  #echo "DEBUG TIMER $debug_counter_count started" >&$fd_original_err
}

debug_timer_end() {
  local result
  ts_diff $debug_timer_start $EPOCHREALTIME
  echo "DEBUG TIMER $debug_counter_count ended: $result" >&$fd_original_err
}

debug_counter() {
  debug_counter_count=${debug_counter_count:-0}
  if (( debug_counter_count++ )); then nothing fi
  reply_to_caller "debug_counter_count=$debug_counter_count"
  echo "DEBUG COUNTER: $debug_counter_count" >&$fd_original_err
}

# usage: cat {some file} | format_number_stream
# will format all numbers found in the stream
format_number_stream() {
  local field=${field:-all}
  if [[ $field == all ]]; then
    perl -wpe '1 while s/(\d+)(\d\d\d)/$1,$2/;'
  else
    perl -ae '1 while $F['$field'] =~ s/(\d+)(\d\d\d)/$1,$2/; print join(" ",@F) . "\n";'
  fi
}

# input:
#   pid   process to check for
# output:
#   process_running  boolean
check_process() {
  if ps $pid &>/dev/null; then
    log_debug "Process $pid exists"
    process_running=t
  else
    log_debug "Process $pid doesn't exist"
    process_running=f
  fi
}

# make sure we clean up after ourselves whether we've launched a background job or allocated resources
# this needs to be run again whenever forking to a subprocess
setup_exit_trap() {
  failure_handler_state_file=$tmp_folder/failure-state-$$
  failure_handler_already_dumped_stack=f
  trap '
    rc=$?
    #echo "EXIT TRAP $BASHPID, BASH_SUBSHELL=$BASH_SUBSHELL" >&$fd_original_err
    if [[ ${debug_on_exit:-} == t ]]; then
      exiting=t
      debug_start
    fi
    if (( rc > 0 && rc < 100 )); then
      if [[ -e $failure_handler_state_file ]]; then
        source $failure_handler_state_file &>/dev/null
        if (( BASH_SUBSHELL == 0 )); then
          rm $failure_handler_state_file &>/dev/null
        fi
      fi
      if [[ $failure_handler_already_dumped_stack == f ]]; then
        if [[ $trace_time == t ]]; then
          trace_time_summarize
        fi
        extra=
        #if [[ ${show_debug_id:-f} != f ]]; then
        if [[ "${fork_debug_id:-}" ]]; then
          extra=" ${DEBUG_COLOR}debug_id=$fork_debug_id$RESET"
        fi
        echo "$extra ${RED}Exited with failure code $rc"
        #if log_level_at_least debug; then
        #  stack_trace
        #fi
        echo "failure_handler_already_dumped_stack=t" >>$failure_handler_state_file
      fi
    fi
    trap - DEBUG ERR EXIT RETURN QUIT &>/dev/null
    #echo "Cleaning up: $cleanup_on_exit" >&$fd_original_err
    eval "${cleanup_on_exit:-}" &>/dev/null
    if (( rc > 0 )); then
      jobs="$(jobs -p)"
      #echo "Killing jobs $jobs" >&$fd_original_err
      if [[ "$jobs" ]]; then
        { kill $jobs; } 2>/dev/null || true
      fi
    fi
    set +TeuExv
    #echo "debug_restart_command=$debug_restart_command" >&$fd_original_err
    if [[ "${debug_restart_command:-}" ]]; then
      if [[ $BASH_SUBSHELL == 0 ]]; then
        eval "exec $debug_restart_command"
      else
        quotes=single shell_quote_var debug_restart_command
        #echo "Passing up debug_restart_command=$debug_restart_command" >&$fd_original_err
        reply_to_caller "debug_restart_command=$debug_restart_command"
      fi
    fi
    ' EXIT

  # trap '
  #   zombie "ERR $BASH_COMMAND"
  #   trap - DEBUG ERR EXIT RETURN QUIT &>/dev/null
  #   set +TeuExv
  #   if [[ ${debug_on_err:-} == t ]]; then
  #     debug_start
  #     echo "Debugging..."
  #   fi
  #   ' ERR

  # trap '
  #   zombie "HUP $BASH_COMMAND"
  #   ' HUP

  # trap '
  #   zombie "ILL $BASH_COMMAND"
  #   ' ILL

  # trap '
  #   zombie "TRAP $BASH_COMMAND"
  #   ' TRAP

  # trap '
  #   zombie "TERM $BASH_COMMAND"
  #   ' TERM

  # trap '
  #   zombie "ALRM $BASH_COMMAND"
  #   ' ALRM

  # trap '
  #   zombie "SEGV $BASH_COMMAND"
  #   ' SEGV

  # trap '
  #   zombie "USR1 $BASH_COMMAND"
  #   ' USR1

  # trap '
  #   zombie "KILL $BASH_COMMAND"
  #   ' KILL

  # trap '
  #   zombie "FPE $BASH_COMMAND"
  #   ' FPE

  # trap '
  #   zombie "BUS $BASH_COMMAND"
  #   ' BUS

  # trap '
  #   zombie "ABRT $BASH_COMMAND"
  #   ' ABRT

  # trap '
  #   zombie "QUIT $BASH_COMMAND"
  #   ' QUIT
  # trap '
  #   zombie "RETURN $BASH_COMMAND"
  #   f=( "${FUNCNAME[@]:1}" )
  #   show_array f
  #   ' RETURN
}
setup_exit_trap

