#!/bin/bash

# Notice that it has parentheses after function name instead of braces. This means it launches in a
# subshell, localizing the variables and function changes
cube_update() (

current_cube=$1

if [[ ! -f "$current_cube/cube-contexxt" ]]; then
  err "cube_update called on $current_cube which is not a cube"
  return 1
fi

parallel_default=t
[ $debug == t ] && parallel_default=f
parallel_execution=${parallel_execution:-${par:-$parallel_default}}
dimensions=( ) dimension_folders=( )

# need to collect dimensions even though we haven't expanded the members yet
gather_dims || return 1

local dim dims dim_string=""
for dim in "${dimensions[@]}"; do
  dims=${dim}s
  if [[ "${!dims:-}" ]]; then
    dim_string+="$dims=[ ${!dims:-} ] "
  else
    dim_string+="$dim=${!dim:-} "
  fi
done
trace 0 "Updating cube $current_cube $dim_string"

begin_function

  init_and_load_context_a

  if [[ "$current_cube" -nt "$current_cube/cube-context" ]]; then
    touchup_cube || fail
  fi

  if [ ${#dimensions[*]} == 0 ]; then
    cell_update "$current_cube" || fail
  else
    cube_update_pivot 0 || fail
  fi

end_function
handle_return

)

gather_dims() {
trace 0 "Gathering dimensions for $current_cube"
begin_function
  if [ -d "$current_cube/dim" ]; then
    begin_for dimension_folder in 
      $(find "$current_cube/dim" -mindepth 1 -maxdepth 1 -type d | sort); doo
      dimension=${dimension_folder##*/}
      if [[ "$dimension" =~ ^[0-9]+- ]]; then
        dimension=${dimension#*-}
      fi
      if [[ ! "$dimension_folder" =~ ^[a-zA-Z0-9_]+$ ]]; then
        err "Invalid dimension name [$dimension] derived from folder $dimension_folder"
        err "Dimensions must only have alphanumeric or _ characters in it."
        fail
      fi
      dimensions+=( $dimension )
      dimension_folders+=( "$dimension_folder" )
    end_for
  fi
end_function
handle_return
}

touchup_cube() {
trace 0 "Touching up $current_cube"
local f
begin_function
  begin_for f in up res down in out tmp log lock key status; doo
    if [ -f "$current_cube/$f" ]; then
      rm "$current_cube/$f" || fail
      mkdir "$current_cube/$f" || fail
    fi
  end_for
  touch "$current_cube/cube-context"
end_function
handle_return
}

# should only be called if there are dimensions remaining to be pivoted. Otherwise cell_update should be called.
cube_update_pivot() {

local index=$1
local dim=${dimensions[$index]} 
local dim_folder=${dimension_folders[$index]}

trace 0 "Pivoting $current_cube: $dim"
begin_function

  if [[ ! -d "$dim_folder" ]]; then
    err "Internal error: cube_update_pivot was called with an index which doesn't corrospond with a dimension folder: $dim_folder"
    fail
  fi

  cube_update "$dim_folder" || fail
  if [[ ! -f "$dim_folder/out/functions" ]]; then
    err "Missing functions file in $dimension_folder/out. It must contain the expand_dim function."
    fail
  fi
  source "$dim_folder/out/functions" || fail
  expand_dim $dim || fail
  local dims=${dim}s
  local values=( ${!dims:-} )

  if [[ ! "$values" ]]; then
    err "Missing value for dimension $dim"
    fail
  fi

  local value processes
  local parallel=f
  if [[ "${#values[*]}" > 1 && "$parallel_execution" == t ]]; then
    parallel=t
    wait_for_low_load || fail
  fi

  begin_for value in "${values[@]}"; doo
    eval "$dim='$value'"
    if [[ ${#dim[*]} > $((index + 1)) ]]; then
      if [[ $parallel == t ]]; then
        cube_update_pivot $((index + 1)) &
        processes+=" $!"
      else
        cube_update_pivot $((index + 1)) || fail
      fi
    else
      if [[ $parallel == t ]]; then
        cell_update "$current_cube" &
        processes+=" $!"
      else
        cell_update "$current_cube" || fail
      fi
    fi
  end_for

  wait_for_sub_processes || fail

end_function
handle_return

}

wait_for_sub_processes() {
if [ $parallel == t ]; then
  trace 0 "Waiting for sub processes to complete"
  local process
  for process in $processes; do
    wait $process &>/dev/null
    if [ $? -gt 0 -a $? -lt 127 ]; then
      trace 0 "Subprocess $process failed to terminate successfully"
      return 1
    fi
  done
fi
}

select_any_cube() {
local current_cube=$1
trace 0 "Testing 'any' cube $current_cube"
begin_function

  init_and_load_status_context_a
  validate_dims || fail
  local needs_update
  does_cube_need_update || fail
  if [ $needs_update == t ]; then
    trace 0 "Update needed"
    fail
  fi

end_function
handle_return
}

update_any_cube() {
local current_cube=$1
trace 0 "Updating 'any' cube $current_cube"
begin_function
  init_and_load_status_context_a
  cube_update_array "$current_cube" || fail
end_function
handle_return
}

cell_update_deps() {
trace 0 "Updating subs of $current_cube"
begin_function

  local dep
  local parallel=f processes
  local dependencies=( $(find "$current_cube/up" -mindepth 1 -maxdepth 1 -type d | sort) )
  # TODO: before launching parallel processes, wait for load/process count
  [[ ${#dependencies[*]} > 1 && $parallel_execution == t ]] && parallel=t

  local any_folder
  begin_for any_folder in ; doo
    
    # check if any cubes are already complete
    local any_selected=
    local options=$(find "$any_folder" -mindepth 1 -maxdepth 1 -type d | sort)
    for dep in $options; do
      select_any_cube "$dep" && { any_selected=$dep; break; }
    done

    # of those that are valid, try to update one by one until successful
    if [ ! "${any_selected:-}" ]; then
      for dep in $options; do
        update_any_cube "$dep" && { any_selected=$dep; break; }
      done
    fi

    # link any cube to parent folder
    if [ "${any_selected:-}" ]; then
      local selected_folder=$any_selected
      [[ $selected_folder =~ .*/(.*/.*) ]] || fail
      selected_folder=${BASH_REMATCH[1]}
      ln -sf "$selected_folder" "$current_cube/up/${any_folder%?}" || fail
    else
      trace -5 "Failed to find valid dependency for $any_folder"
      fail
    fi

  end_for

  # TODO: if dep starts with a number, it must be executed sequentially. The rest are in parallel
  begin_for dep in $(find "$current_cube/up" -not -name '*\?' -mindepth 1 -maxdepth 1 -type d | sort); doo
    local down_path="$dep/down/${current_cube##*/}"
    if [ ! -e "$down_path" ]; then
      ln -sf "$current_cube" "$down_path" || fail
    elif [ "$(realpath "$down_path")" != "$current_cube" ]; then
      local variant=2
      begin_while true; doo
        if [ ! -e "$down_path$variant" ]; then
          ln -sf "$current_cube" "$down_path$variant" || fail
          break
        elif [ "$(realpath "$down_path$variant")" == "$current_cube" ]; then
          break
        fi
        let variant++
      end_while
    fi

    if [ $parallel == t ]; then
      called_from=$short_cube/up cube_update_row "$dep" &
      processes+=" $!"
    else
      called_from=$short_cube/up cube_update_row "$dep" || fail
    fi
  end_for

  wait_for_sub_processes || fail

end_function
handle_return
}

read_lock_deps() {
trace 0 "Obtaining read locks for subs of $current_cube"
begin_function

  local dep lock_fd
  begin_for dep in $(find "$current_cube/up" -mindepth 1 -maxdepth 1 -not -name '*\?' -type d | sort); doo
    init_and_load_status_context_a
    if [ -d "$dep/lock" ]; then
      exec {lock_fd}<"$dep/lock" || fail
      flock -s -w $lock_timeout $lock_fd || {
        err "Failed to get read lock for dep $dep of $current_cube"
        fail
        }
    fi
  end_for

end_function
handle_return
}

write_lock_cube() {
trace 0 "Obtaining write lock for $current_cube"
begin_function

  local lock_fd
  exec {lock_fd}<"$current_cube/lock" || fail
  flock -x -w $lock_timeout $lock_fd || {
    err "Failed to get write lock for $current_cube"
    fail
    }

end_function
handle_return
}

write_persist_file() {
  echo "
update_id=$update_id
cooldown_delay=$cooldown_delay
consecutive_failures=$consecutive_failures
" >$status_path/persist || fail
}

maybe_apply_cooldown() {
begin_function
  # If cell recently failed, wait until cooldown period is complete
  if [[ $consecutive_failures > 0 ]]; then
    get_cooldown_delay || fail
    if [[ $cooldown_delay > 0 ]]; then
      trace 0 "Too many errors have occurred, waiting for cooldown period of $cooldown_delay seconds"
      new_stage cooldown || fail
      sleep $cooldown_delay
    fi
  else
    cooldown_delay=1
  fi
end_function
handle_return
}

cell_update() {

local current_cube=$1

local dim dims dim_string="" update_id cell_id= cell_dim_part value stage_start_time previous_stage
for dim in "${dimensions[@]}"; do
  value="${!dim}"
  dim_string+="$dim=$value "
  cell_dim_part+="$value:"
done

local log_path= status_path= out_path=

if [[ -d $current_cube/log ]]; then
  log_path=$current_cube/log$cell_id
  [[ ! -d $log_path ]] && { mkdir $log_path || fail; }
  tee_output_to $log_path/current-update-log
fi

if [[ -d $current_cube/status ]]; then
  status_path=$current_cube/status$cell_id
  [[ ! -d $status_path ]] && { mkdir $status_path || fail; }
fi

if [[ -d $current_cube/out ]]; then
  out_path=$current_cube/out$cell_id
  if [[ ! -d $out_path ]]; then
    mkdir $out_path || fail
    touch -t 197001010000 $out_path || fail
  fi
fi

trace 0 "Updating cell $current_cube $dim_string"

begin_function

  if [[ "$cell_dim_part" ]]; then
    cell_dim_part=${cell_dim_part%:}
    cell_id=/$cell_dim_part
    if [[ ${high_volume_cube:-f} == t ]]; then
      local hash=$(echo "$cell_dim_part" | cksum) 
      hash=${hash:0:2}
      cell_id+=/$hash
    fi
  fi

  init_stage || fail
  new_stage begin-update || fail

  if [[ "$status_path" ]]; then

    local consecutive_failures=${consecutive_failures:-0}
    [[ -f "$status_path/persist" ]] && { source "$status_path/persist" || fail; }

    if [[ "${update_id:-}" ]]; then
      let update_id++
    else
      update_id=1000
    fi

    maybe_apply_cooldown || fail
    write_persist_file || fail

  else
    update_id=1000
  fi

  # TODO: readlock before needs-update check

  new_stage check-needs-update || fail
  # freshness check first
  local needs_update
  does_cube_need_update || fail
  if [ $needs_update == f ]; then
    trace 0 "Update not needed"
    succeed
  fi

  # TODO: check all dep resources to ensure they will be available when we start

  local lock_timeout=${lock_timeout:-30}

  local read_locks=''
  if [ -d "$current_cube/up" ]; then
    new_stage update-deps || fail
    cell_update_deps || fail

    new_stage read-locks || fail
    read_lock_deps || fail
  fi

  new_stage wait-for-load || fail
  wait_for_low_load || fail

  new_stage write-lock || fail
  if [ -d "$current_cube/lock$cell_id" ]; then
    write_lock_cube || fail
  fi

  # TODO: obtain resources

  new_stage load-update-context || fail
  init_and_load_update_context_a

  local in_path="$current_cube/in"
  [ -n "$cell_id" ] && [ -d "$current_cube/in$cell_id" ] && in_path="$current_cube/in$cell_id"

  # TODO: only use tmp path here if folder exists, otherwise use system tmp folder
  local tmp_path="$current_cube/tmp$cell_id"
  if [ -d "$tmp_path" ]; then
    rm -rf "$tmp_path" || fail
  fi
  mkdir "$tmp_path" || fail

  mkdir -p "$out_path.new" || fail

  local need_decrypt file
  begin_for file in $(find "$in_path" -name '*.crypt' -type f); doo
    file=${file#$in_path}
    file=${file%.crypt}
    if [ -f "$out_path/$file" ]; then
      cp "$out_path/$file" "$out_path.new/$file" || fail
    else
      need_decrypt+="$file "
    fi
  end_for

  if [ "$need_decrypt" ]; then
    new_stage decrypt || fail
    begin_for file in $need_decrypt; doo
      decrypt_file "$in_path/$file.crypt" "$out_path.new/$file" || fail
    end_for
  fi

  new_stage execute-update || fail

  local start_time=$EPOCHSECONDS
  local update_successful=f
  execute_update && update_successful=t
  local duration_of_update=$((EPOCHSECONDS-start_time))
  local success_string=good
  [ $update_successful == f ] && success_string=bad
  echo "start:$start_time duration:$duration_of_update from:$called_from result:$success_string" >>$log_path/history || fail

  mv $log_path/update-log-current $log_path/update-log-$update_id || fail
  if [ $update_successful == t ]; then

    trace 0 "Update successful."
    new_stage succeeded || fail

    if [ -d "$out_path.new" -a $update_successful == t ]; then
      if ! diff -r "$out_path" "$out_path.new" >/dev/null; then
        [ -d "$out_path.old" ] && rm -rf "$out_path.old" 2>/dev/null
        mv "$out_path" "$out_path.old" || fail
        mv "$out_path.new" "$out_path" || fail
        mv "$current_cube/status$cell_id/current" "$current/status$cell_id/last-success-changed" || fail
      else
        rm -rf "$out_path.new" || fail
        mv "$current_cube/status$cell_id/current" "$current/status$cell_id/last-success-not-changed" || fail
      fi
    fi

    touch -d @$start_time "$out_path" || fail

    if [ -d "$current_cube/log" ]; then
      untee_output
      ln -s $log_path/update-log-last-success $log_path/update-log-$update_id || fail
      # TODO: save all logs if debug folder exists
    fi

    # TODO: push update to dependencies
    # TODO: record successful updates in execution log (cell, update id and timestamp)

    if [ -d "$tmp_path" ]; then
      rm -rf "$tmp_path" || fail
    fi

    consecutive_failures=0
    write_persist_file

  else

    trace 0 "Update failed."
    new_stage failed || fail

    mv "$current_cube/status$cell_id/current" "$current/status$cell_id/last-failure" || fail

    if [ -d "$current_cube/log" ]; then
      untee_output
      ln -s $log_path/update-log-last-failure $log_path/update-log-$update_id || fail
      # TODO: save all logs if debug folder exists
    fi
    # TODO: record failed updates in execution log (cell, update id and timestamp)

    let consecutive_failures++
    write_persist_file

  fi

end_function
handle_return

}

# not used?
derive_row_ids() {
# todo: needs to be fixed to support multiple rows and use plural dims
local dimension_count="${#dimensions[*]}" 
if [ $dimension_count -gt 0 ]; then
  local dimension default dimension_with_default
  row_id=
  for dimension_with_default in "${dimensions[@]}"; do
    read dimension default <<<$dimension_with_default
    local var_defined=t
    declare -p "$dimension" &>/dev/null || var_defined=f
    if [ $var_defined == f ]; then
      if [ "$default" ]; then
        eval "$dimension='$default'"
      else
        err "Required var $dimension not defined, and no default was provided."
        fail
      fi
    fi
    if [[ "${!dimension}" =~ [$TAB$NL\ :] ]]; then
      err "Dimension $dimension contains invalid characters: [${!dimension}]. It must not contain white space or colons."
      fail
    fi
    row_id+="${!dimension}:"
  done
  row_id=${row_id%:}
  cell_id="/$row_id"
else
  row_id="only"
  cell_id=""
fi
}

wait_for_low_load() {
local cube_max_load=${cube_max_load:-10}
local cube_load_wait_timeout=${cube_load_wait_timeout:-600}
local current_load=$(uptime | sed -E 's/.*averages: ([0-9]*).*/\1/')
if [ $current_load -gt $cube_max_load ]; then
  trace 5 "Load average is too high ($current_load > $cube_max_load), waiting until things cool down first."
  local time_waited=0
  while [ $current_load -gt $cube_max_load ]; do
    current_load=$(uptime | sed -E 's/.*averages: ([0-9]*).*/\1/')
    sleep 5; let time_waited+=5
    if [ "$cube_load_wait_timeout" -gt 0 -a $time_waited -ge $cube_load_wait_timeout ]; then
      err "Timed out waiting for cpu load to be low enough. Aborting"
      return 1
    fi
  done
fi
return 0
}

tee_output_to() {
local target=$1
exec 1> >(tee "$target")
exec 2> >(tee -a "$target")
eval "exec $fd_trace> >(tee -a '$target')"
}

untee_output() {
exec 1>&$fd_original_out
exec 2>&$fd_original_err
eval "exec $fd_trace>&$fd_original_trace"
}

init_stage() {
previous_stage=
start_time=
}

new_stage() {
local stage=$1
if [ "${previous_stage:-}" ]; then
  trace 5 "Finished stage $previous_stage (took $(echo '$EPOCHSECONDS - $stage_start_time' | bc) seconds)"
fi
echo "$stage $EPOCHSECONDS" >>"$log_path/current-stages"
trace 5 "Starting stage $stage"
stage_start_time=$EPOCHSECONDS
previous_stage=$stage
}

does_cube_need_update() {
begin_function

  needs_update=f

  # nothing needs to be done in execution phase if execute_update function isn't defined
  type execute_update &>/dev/null || succeed

  if [ -d "$current_cube/in" ]; then
    if [ "$current_cube/in" -nt "$current_cube/out$cell_id" -o "$current_cube/in$cell_id" -nt "$current_cube/out$cell_id" ]; then
      trace 0 "Local changes were made, needs update"
      needs_update=t
      succeed
    fi
  fi

  if [ -d "$current_cube/up" ]; then
    if [ "$current_cube/up" -nt "$current_cube/out$cell_id" ]; then
      trace 0 "Upstream changes were made, needs update"
      needs_update=t
      succeed
    fi
  fi

  if [ "${fresh:-}" ]; then
    local fresh_seconds
    convert_to_seconds $fresh fresh_seconds || fail
    local fresh_cutoff=$((EPOCHSECONDS-fresh_seconds))
    local out_timestamp=$(date -r "$current_cube/out$cell_id" +%s)
    if [ $out_timestamp -lt $fresh_cutoff ]; then
      trace 0 "Freshness requirement ($fresh) not met, needs update"
      needs_update=t
      succeed
    fi
  fi

end_function
handle_return
}
