#!/bin/bash

type -t cube_update >/dev/null && return 0

# current_cube must be set before this is used
alias init_and_load_context_a='
  init_context "$current_cube" || fail
  load_context "$current_cube" || fail
'

cube_update() {

local current_cube=$1
# set this before calling this function to maintain a read lock even
#   after this update completes. Used for upstream dependency locking. 
local keep_read_locks=${keep_read_locks:-f}
local keep_write_locks=${keep_write_locks:-f}

local parallel_default=t
[ $debug == t ] && parallel_default=f
local parallel_execution=${parallel_execution:-${par:-$parallel_default}}
local save_prefix=${save_prefix:-}
local dimensions=() dimension_folders=() localize_dim_vars dim_string="" 

# need to collect dimensions even though we haven't expanded the members yet
gather_dims || return 1

trace 0 "Updating cube $current_cube $dim_string"

begin_function

  # is this an 'any' cell?
  if [[ ${current_cube%\?} != $current_cube ]]; then
    select_any_cube || fail
    succeed
  fi

  if [[ ! -f "$current_cube/cube-context" ]]; then
    err "cube_update called on $current_cube which is not a cube"
    fail
  fi

  if [[ "$current_cube" -nt "$current_cube/cube-context" ]]; then
    touchup_cube || fail
  fi

  eval "$localize_dim_vars" || fail

  if [ ${#dimensions[*]} == 0 ]; then
    cell_update || fail
  else
    cube_update_pivot 0 || fail
  fi

end_function
handle_return

}

gather_dims() {
trace 0 "Gathering dimensions for $current_cube"
local dimension dimension_folder dimension_plural
localize_dim_vars=
begin_function
  if [ -d "$current_cube/dim" ]; then
    begin_for dimension_folder in \
      $(find "$current_cube/dim" -mindepth 1 -maxdepth 1 -type d | sort); doo
      dimension=${dimension_folder##*/}
      if [[ "$dimension" =~ ^[0-9]+- ]]; then
        dimension=${dimension#*-}
      fi
      if [[ ! "$dimension_folder" =~ ^[a-zA-Z0-9_]+$ ]]; then
        err "Invalid dimension name [$dimension] derived from folder $dimension_folder"
        err "Dimensions must only have alphanumeric or _ characters in it."
        fail
      fi
      dimension_plural=${dimension}s
      dimensions+=( $dimension )
      dimension_folders+=( "$dimension_folder" )
      localize_dim_vars+="local $dimension $dimension_plural; "
      if [[ "${!dimensions:-}" ]]; then
        dim_string+="$dimensions=[ ${!dimensions:-} ] "
      else
        dim_string+="$dimension=${!dimension:-} "
      fi
    end_for
  fi
end_function
handle_return
}

touchup_cube() {
trace 0 "Touching up $current_cube"
local f
begin_function
  begin_for f in debug up res down in out tmp log lock key status; doo
    if [ -f "$current_cube/$f" ]; then
      rm "$current_cube/$f" || fail
      mkdir "$current_cube/$f" || fail
    fi
  end_for
  touch "$current_cube/cube-context"
end_function
handle_return
}

# should only be called if there are dimensions remaining to be pivoted. Otherwise cell_update should be called.
cube_update_pivot() {

local index=$1
local dim=${dimensions[$index]} 
local dim_folder=${dimension_folders[$index]}

trace 0 "Pivoting $current_cube: $dim"
begin_function

  if [[ ! -d "$dim_folder" ]]; then
    err "Internal error: cube_update_pivot was called with an index which doesn't corrospond with a dimension folder: $dim_folder"
    fail
  fi

  save_prefix=dim cube_update "$dim_folder" || fail

  if [[ ! -f "$dim_folder/out$dim_id/functions" ]]; then
    err "Missing functions file in $dim_folder/out$dim_id. It must contain the expand_dim function."
    fail
  fi

  source "$dim_folder/out$dim_id/functions" || fail

  if ! type expand_dim &>/dev/null; then
    err "$dim_folder/out$dim_id/functions does not contain expand_dim function"
    fail
  fi

  expand_dim $dim || fail
  local dims=${dim}s
  local values=( ${!dims:-} )

  if [[ ! "$values" ]]; then
    err "Missing value for dimension $dim"
    fail
  fi

  local value processes
  local parallel=f
  if [[ "${#values[*]}" > 1 && "$parallel_execution" == t ]]; then
    parallel=t
    wait_for_low_load || fail
  fi

  begin_for value in "${values[@]}"; doo
    eval "$dim='$value'"
    if [[ ${#dim[*]} > $((index + 1)) ]]; then
      if [[ $parallel == t ]]; then
        cube_update_pivot $((index + 1)) &
        processes+=" $!"
      else
        cube_update_pivot $((index + 1)) || fail
      fi
    else
      local fd=
      local cell_id dim_string
      if [[ $parallel == t ]]; then
        cell_update &
        processes+=" $!"
      else
        cell_update || fail
      fi
    fi
  end_for

  wait_for_sub_processes || fail

end_function
handle_return

}

wait_for_sub_processes() {
if [[ $parallel == t && "$processes" ]]; then
  trace 0 "Waiting for sub processes to complete"
  local process
  for process in $processes; do
    wait $process &>/dev/null
    if [[ $? > 0 && $? < 127 ]]; then
      trace 0 "Subprocess $process failed to terminate successfully"
      return 1
    fi
  done
fi
}

select_any_cube() {

trace 0 "Selecting an 'any' cube from $current_cube"
begin_function

  local found= f
  local subs="$(find $current_cube -mindepth 1 -maxdepth 1 -type d | sort)"

  begin_for f in $subs; doo
    quick_check=t cube_update $f && {
      found=$f
      succeed
    }
  end_for

  [[ ! "$found" ]] && begin_for f in $subs; doo
    cube_update $f && {
      found=$f
      succeed
    }
  end_for

  if [[ ! "$found" ]]; then
    err "Couldn't find a valid 'any' cube for $current_cube"
    fail
  fi

end_function
handle_return

}

cell_get_resources() {
trace 0 "Getting resources for $current_cube"
begin_function

  local res dep_fd
  local parallel=f processes
  local parallel_resources=( $(
    find "$current_cube/res" -mindepth 1 -maxdepth 1 -type d \
      -not -regex "$current_cube/res/[0-9]+-.*" 
    ) )
  local serial_resources=( $(
    find "$current_cube/res" -mindepth 1 -maxdepth 1 -type d \
      -regex "$current_cube/res/[0-9]+-.*" \
    | sort) )

  local total_parallel=${#parallel_resources[*]}
  [[ "$sequential_resources" ]] && let total_parallel++

  if [[ $total_parallel > 1 && $parallel_execution == t ]]; then
    parallel=t
    wait_for_low_load || fail
  fi

  local saved_id= saved_path= res_name
  begin_for res in ${parallel_resources[*]}; doo
    update_resource "$res" &
  end_for

  if [[ $parallel == t ]]; then
    update_serial_resources &
  else
    update_serial_resources || fail
  fi

  wait_for_sub_processes || fail

end_function
handle_return
}

update_resource() {
local res=$1
local res_name=${res##*/}
save_prefix=res_$res_name keep_write_locks=t cube_update $res
}

update_serial_resources() {
begin_for res in ${serial_resources[*]}; doo
  update_resource $res || return 1
end_for
return 0
}

cell_update_deps() {
trace 0 "Updating upstream cells of $current_cube"
begin_function

  local dep 
  local parallel=f processes
  local parallel_deps=( $(
    find "$current_cube/up" -mindepth 1 -maxdepth 1 -type d \
      -not -regex "$current_cube/up/[0-9]+-.*" 
    ) )
  local serial_deps=( $(
    find "$current_cube/up" -mindepth 1 -maxdepth 1 -type d \
      -regex "$current_cube/up/[0-9]+-.*" \
    | sort) )

  local total_parallel=${#parallel_deps[*]}
  [[ "$sequential_deps" ]] && let total_parallel++

  if [[ $total_parallel > 1 && $parallel_execution == t ]]; then
    parallel=t
    wait_for_low_load || fail
  fi

  begin_for dep in ${parallel_deps[*]}; doo
    update_dep "$dep" &
  end_for

  if [[ $parallel == t ]]; then
    update_serial_deps &
  else
    update_serial_deps || fail
  fi

  wait_for_sub_processes || fail

end_function
handle_return
}

update_serial_deps() {
begin_for dep in "${serial_deps[@]}"; doo
  update_dep "$dep" || return 1
end_for
return 0
}

update_dep() {
local dep=$1
local dep_name=${dep##*/}
save_prefix=up_$dep_name keep_read_locks=t cube_update $dep
}

get_read_lock() {
local lock_path=$1
local timeout=${2:-$lock_timeout}
flock -s -w $lock_timeout $lock_fd || {
  err "Failed to get read lock for $lock_path within $timeout seconds"
  return 1
  }
}

get_write_lock() {
local lock_path=$1
local timeout=${2:-$lock_timeout}
flock -e -w $lock_timeout $lock_fd || {
  err "Failed to get write lock for $lock_path within $timeout seconds"
  return 1
  }
}

unlock() {
flock -u $1
}

write_persist_file() {
  echo "
update_id=$update_id
cooldown_delay=$cooldown_delay
consecutive_failures=$consecutive_failures
" >$status_path/persist || fail
}

maybe_apply_cooldown() {
begin_function
  # If cell recently failed, wait until cooldown period is complete
  if [[ $consecutive_failures > 0 ]]; then
    get_cooldown_delay || fail
    if [[ $cooldown_delay > 0 ]]; then
      trace 0 "Too many errors have occurred, waiting for cooldown period of $cooldown_delay seconds"
      new_stage cooldown || fail
      sleep $cooldown_delay
    fi
  else
    cooldown_delay=1
  fi
end_function
handle_return
}

# produces: cell_id, dim_string
get_cell_id() {

local dim dims cell_dim_part= value hash 
dim_string=
cell_id=

for dim in "${dimensions[@]}"; do
  value="${!dim}"
  dim_string+="$dim=$value "
  if [[ ${#value} < 32 && "$value" =~ ^[A-Za-z0-9_\.:\-]+$ ]]; then
    cell_dim_part+="$value,"
  else
    hash=$(echo "$value" | cksum -a md5 | awk '{ print $4 }')
    cell_dim_part+="${hash:0:8},"
  fi
done

if [[ "$cell_dim_part" ]]; then
  cell_dim_part=${cell_dim_part%:}
  cell_id=/$cell_dim_part
  if [[ ${high_volume_cube:-f} == t ]]; then
    hash=$(echo "$cell_dim_part" | cksum -a md5 | awk '{ print $4 }') 
    hash=${hash:0:2}
    cell_id=/$hash/$cell_dim_part
  fi
fi

if [[ "${save_prefix:-}" ]]; then
  eval "${save_prefix}_id=$cell_id"
  eval "${save_prefix}_path=$current_cube"
fi

return 0

}

cell_update() {
local fd= extra_fds=
get_cell_id || return 1
if [[ -d $current_cube/lock$cell_id && ($keep_read_locks == t || $keep_write_locks == t) ]]; then
  exec {fd}<$current_cube/lock$cell_id || return 1
fi
outer_lock_fd=$fd cell_update_inner || return 1
return 0
}

# Notice that it has parentheses after function name instead of braces. This means it launches in a
# subshell, localizing the variables and function changes
cell_update_inner() (

local lock_timeout=${lock_timeout:-30} update_id stage_start_time previous_stage
local lock_fd quick_check=${quick_check:-f} 
local allow_slow_updates=${allow_slow_updates:-t} update_is_slow=f
local debug_path= down_path= in_path= lock_path= log_path= status_path= out_path= tmp_path= up_path= res_path=
local tmp_folder=${tmp_folder:-/tmp}

trace 0 "Updating cell $current_cube $dim_string"

begin_function

  local start_time=$EPOCHSECONDS
  init_and_load_context_a

  cell_validate || fail
  cell_feature_setup || fail

  if [[ "$lock_path" ]]; then
    trace 0 "Getting read lock for cell"
    get_read_lock "$lock_path" || fail
  fi

  trace 0 "Checking if update is needed"

  # freshness check first
  local needs_update
  does_cube_need_update || fail
  if [[ $needs_update == f ]]; then
    if [[ $quick_check == t ]]; then
      trace 5 "Quick check finished: Update not needed"
    else
      trace 0 "Update not needed"
    fi
    succeed
  fi

  if [[ $quick_check == t ]]; then
    trace 5 "Quick check finished: Update needed"
    fail
  fi

  cell_pre_update || fail

  local update_successful=t

  if type execute_update &>/dev/null; then
    new_stage execute-update || fail
    execute_update || update_successful=f
  fi

  cell_post_update || fail

  # unlocks happen automatically when this subprocess closes, in addition to filehandle closing

end_function
handle_return

)

cell_post_update() {

begin_function

  new_stage complete || fail
  local end_time=$EPOCHSECONDS

  if [[ $update_successful == t ]]; then
    trace 0 "Update successful."
  else
    trace 0 "Update failed."
  fi

  if [ $update_successful == t ]; then

    if [[ -d "$out_path.new" ]]; then
      if ! diff -r "$out_path" "$out_path.new" >/dev/null; then
        [[ -d "$out_path.old" ]] && rm -rf "$out_path.old"
        mv "$out_path" "$out_path.old" || fail
        mv "$out_path.new" "$out_path" || fail
      else
        rm -rf "$out_path.new" || fail
      fi
    fi

    if [[ "$out_path" ]]; then 
      touch -d @$start_time "$out_path" || fail
    fi

    if [ -d "$tmp_path" ]; then
      rm -rf "$tmp_path" || fail
    fi

    consecutive_failures=0

  else

    let consecutive_failures++

  fi

  write_persist_file || fail

  if [[ "$log_path" ]]; then

    local success_string=good
    [[ $update_successful == f ]] && success_string=bad
    local duration_of_update=$((end_time-start_time))
    echo "update_id=$update_id start=$start_time duration=$duration_of_update from=$called_from" \
      "result=$success_string $dim_string" >>$log_path/history || fail

    untee_output || fail

    if [[ "$debug_path" ]]; then
      mv $log_path/update-log-id-* $debug_path/ &>/dev/null
      mv $log_path/stage-timing-id-* $debug_path/ &>/dev/null
    else
      rm $log_path/update-log-id-* &>/dev/null
      mv $log_path/stage-timing-id-* &>/dev/null
    fi

    mv $log_path/update-log-current $log_path/update-log-id-$update_id || fail
    ln $log_path/update-log-id-$update_id $log_path/update-log-last-$success_string || fail
    mv $log_path/stage-timing-current $log_path/stage-timing-id-$update_id || fail
    ln $log_path/stage-timing-id-$update_id $log_path/stage-timing-last-$success_string || fail

  fi

  if [[ "$outer_lock_fd" && $keep_write_locks == f && $keep_read_locks == t ]]; then
    # convert back to read lock so it doesn't change when downstream update is proceeding
    get_read_lock "$lock_path" || fail
  fi

end_function
handle_return

}

cell_pre_update() {

begin_function

  init_stage || fail
  new_stage begin-update || fail

  if [[ -d $current_cube/log ]]; then
    log_path=$current_cube/log$cell_id
    [[ ! -d $log_path ]] && { mkdir $log_path || fail; }
    tee_output_to $log_path/update-log-current
  fi

  if [[ "$status_path" ]]; then

    local consecutive_failures=${consecutive_failures:-0}
    [[ -f "$status_path/persist" ]] && { source "$status_path/persist" || fail; }

    if [[ "${update_id:-}" ]]; then
      let update_id++
    else
      update_id=1000
    fi

    maybe_apply_cooldown || fail
    write_persist_file || fail

  else
    update_id=1000
  fi

  if [[ "$up_path" ]]; then
    new_stage update-deps || fail
    cell_update_deps || fail
  fi

  if [[ "$res_path" ]]; then
    trace 0 "Getting resources for cell"
    new_stage get-resources || fail
    cell_get_resources "$res_path" || fail
  fi

  new_stage write-lock || fail
  if [[ "$lock_path" ]]; then
    trace 0 "Getting write lock for cell"
    new_stage write-lock-cell || fail
    get_write_lock "$lock_path" || fail
  fi

  if [[ "$out_path" ]]; then
    if [[ -d $out_path.new ]]; then 
      rm -rf $out_path.new || fail
    fi
    mkdir $out_path.new || fail
  fi

end_function
handle_return

}

cell_validate() {

begin_function

  if ! validate_dims; then
    trace 0 "Dims for this cube aren't valid. Maybe we can try another."
    fail
  fi

  if [[ $allow_slow_updates == f && $update_is_slow == t ]]; then
    trace 0 "Update is too slow to meet requirements, let's try a different strategy"
    fail
  fi

end_function
handle_return

}

cell_feature_setup() {

begin_function

  if [[ -d $current_cube/debug ]]; then
    debug_path=$current_cube/debug$cell_id
    [[ ! -d $debug_path ]] && { mkdir $debug_path || fail; }
  fi

  if [[ -d $current_cube/down ]]; then
    down_path=$current_cube/down$cell_id
    if [[ ! -d $down_path ]]; then
      down_path=$current_cube/down || fail
    fi
  fi

  if [[ -d $current_cube/in ]]; then
    in_path=$current_cube/in$cell_id
    [[ ! -f $in_path ]] && in_path=$current_cube/in
  fi

  if [[ -d $current_cube/lock ]]; then
    lock_path=$current_cube/lock$cell_id
    [[ ! -f $lock_path ]] && { touch $lock_path || fail; }
    if [[ "$outer_lock_fd" ]]; then
      lock_fd=$outer_lock_fd
    else
      exec {lock_fd}<>"$lock_path" || fail
    fi
  fi

  if [[ -d $current_cube/status ]]; then
    status_path=$current_cube/status$cell_id
    [[ ! -d $status_path ]] && { mkdir $status_path || fail; }
  fi

  if [[ -d $current_cube/out ]]; then
    out_path=$current_cube/out$cell_id
    if [[ ! -d $out_path ]]; then
      mkdir $out_path || fail
      touch -t 197001010000 $out_path || fail
    fi
  fi

  if [[ -d $current_cube/tmp ]]; then
    tmp_path=$current_cube/tmp$cell_id
    [[ ! -d $tmp_path ]] && { mkdir $tmp_path || fail; }
    tmp_folder=$tmp_path
  fi

  if [[ -d $current_cube/up ]]; then
    up_path=$current_cube/up$cell_id
    if [[ ! -d $up_path ]]; then
      up_path=$current_cube/up || fail
    fi
  fi

  if [[ -d $current_cube/res ]]; then
    res_path=$current_cube/res$cell_id
    if [[ ! -d $res_path ]]; then
      res_path=$current_cube/res || fail
    fi
  fi

end_function
handle_return

}

wait_for_low_load() {
local cube_max_load=${cube_max_load:-10}
local cube_load_wait_timeout=${cube_load_wait_timeout:-600}
local current_load=$(uptime | sed -E 's/.*averages: ([0-9]*).*/\1/')
if [[ $current_load > $cube_max_load ]]; then
  trace 0 "Load average is too high ($current_load > $cube_max_load)," \
    "waiting until things cool down first."
  local time_waited=0
  while [[ $current_load > $cube_max_load ]]; do
    current_load=$(uptime | sed -E 's/.*averages: ([0-9]*).*/\1/')
    sleep 5; let time_waited+=5
    if [[ "$cube_load_wait_timeout" > 0 && ! $time_waited < $cube_load_wait_timeout ]]; then
      err "Timed out waiting for cpu load to be low enough. Aborting"
      return 1
    fi
  done
fi
return 0
}

tee_output_to() {
local target=$1
exec 1> >(tee "$target")
exec 2> >(tee -a "$target")
eval "exec $fd_trace> >(tee -a '$target')"
}

untee_output() {
exec 1>&$fd_original_out
exec 2>&$fd_original_err
eval "exec $fd_trace>&$fd_original_trace"
}

init_stage() {
previous_stage=
start_time=
}

new_stage() {
local stage=$1
if [[ "${previous_stage:-}" ]]; then
  trace 5 "Finished stage $previous_stage" \
    "took $(echo '$EPOCHSECONDS - $stage_start_time' | bc) seconds)"
fi
[[ "$log_path" ]] && echo "$stage $EPOCHSECONDS" >>"$log_path/stage-timing-current"
trace 5 "Starting stage $stage"
stage_start_time=$EPOCHSECONDS
previous_stage=$stage
}

does_cube_need_update() {
begin_function

  needs_update=t

  [[ ! "$out_path" ]] && succeed
  
  if [[ "$in_path" && "$out_path" ]]; then
    if [[ "$in_path" -nt "$out_path" ]]; then
      trace 5 "Local changes were made, needs update"
      succeed
    fi
  fi

  if [[ "$up_path" && "$out_path" ]]; then
    if [[ "$up_path" -nt "$out_path" ]]; then
      trace 5 "Upstream changes were made, needs update"
      succeed
    fi
  fi

  if [[ "${fresh:-}" ]]; then
    local fresh_seconds
    convert_to_seconds $fresh fresh_seconds || fail
    local fresh_cutoff=$((EPOCHSECONDS-fresh_seconds))
    local out_timestamp=$(date -r "$out_path" +%s)
    if [ $out_timestamp -lt $fresh_cutoff ]; then
      trace 5 "Freshness requirement ($fresh) not met, needs update"
      succeed
    fi
  fi

  if [[ "$up_path" ]]; then
    local deps=( $(find "$current_cube/up" -mindepth 1 -maxdepth 1 -type d) )
    local dep
    begin_for dep in ${deps[*]}; doo
      if ! quick_check=t cube_update "$dep"; then
        # if cube_update fails, then an update is needed
        trace 5 "Upstream $dep needs update"
        succeed 
      fi
    end_for
  fi

  needs_update=f

end_function
handle_return
}

init_context() {

  local current_cube=$1 high_volume=f cell_locks=t cell_logs=f

  reset_expand_dim

  # this may be overridden to provide a custom cooldown calculation
  get_cooldown_delay() {
    [[ -z "${cooldown_delay:-}" ]] && cooldown_delay=1
    let cooldown_delay*=2
  }

  execute_update_decrypt() {
    if [[ "$in_path" && "$out_path" ]]; then
      local need_decrypt file
      begin_for file in $(find "$in_path" -name '*.safe' -type f); doo
        file=${file#$in_path}
        file=${file%.safe}
        if [[ -f $out_path/$file && $out_path/$file -nt $in_path/$file ]]; then
          ln $out_path/$file $out_path.new/$file || fail
        else
          decrypt_file "$in_path/$file.safe" "$out_path.new/$file" || fail
        fi
      end_for
    fi
    return 0
  }

  execute_update_copy() {
    if [[ "$in_path" && "$out_path" ]]; then
      rsync -a $in_path/ $out_path.new/ || return 1
    fi
    return 0
  }

  # override this to implement custom update logic
  execute_update() {
    execute_update_decrypt || return 1
    execute_update_copy || return 1
  }

}

reset_expand_dim() {

  # override this in cubes to support aliases, dimension groups, and defaults
  # should store values in plural form of var, and only plural form should be used after this
  # should fail (return 1) if any values are invalid, or if required value is missing
  expand_dim() {
    local dimension=$1; shift
    local dimension_plural=${dimension_plural}s; shift
    local value=${!dimension:-${!dimension_plural:-}}
    [ -z "$value" ] && return 1
    eval "$dimension_plural=\$value"
    return 0
  }

  # usually this doesn't need to be overridden, since it uses expand_dim to determine if it's valid
  validate_dims() {
    for dim in "${dimensions[@]}"; do
      if ! expand_dim "$dim"; then
        return 1
      fi
    done
    return 0
  }

}

load_context() {
local f=$1 
local logical_parent=${f%/*}
local physical_parent=$(realpath "$logical_parent")
handler_folders=( )

if [ "${#logical_parent}" -gt 1 ]; then
  if [ "$physical_parent" != "$logical_parent" ]; then
    load_physical_context_before "$physical_parent" || return 1
    load_logical_context_before "$physical_parent" || return 1
  else
    load_physical_context_before "$logical_parent" || return 1
  fi
fi

[ -f "$f/cube-context" ] && source "$f/cube-context"
[ -f "$f/cube-context-after" ] && source "$f/cube-context-after"
[ -d "$f/handlers" ] && handler_folders+=( "$f/handlers" )

if [ "${#logical_parent}" -gt 1 ]; then
  if [ "$physical_parent" != "$logical_parent" ]; then
    load_logical_context_after "$physical_parent" || return 1
    load_physical_context_after "$physical_parent" || return 1
  else
    load_physical_context_after "$logical_parent" || return 1
  fi
fi

return 0
}

load_physical_context_before() {
local f=$1 
local physical_parent=${f%/*}
if [ "${#physical_parent}" -gt 1 ]; then
  load_physical_context_before "$physical_parent" || return 1
fi
[ -f "$f/cube-context" ] && source "$f/cube-context"
return 0
}

load_physical_context_after() {
local f=$1 
local physical_parent=${f%/*}
[ -f "$f/cube-context-after" ] && source "$f/cube-context-after"
[ -d "$f/handlers" ] && handler_folders+=( "$f/handlers" )
if [ "${#physical_parent}" -gt 1 ]; then
  load_physical_context_after "$physical_parent" || return 1
fi
return 0
}

load_logical_context_before() {

local f=$1 
local logical_parent=${f%/*}
local physical_parent=$(realpath "$logical_parent")

if [ "${#logical_parent}" -gt 1 ]; then
  if [ "$physical_parent" != "$logical_parent" ]; then
    load_physical_context_before "$physical_parent" || return 1
    load_logical_context_before "$physical_parent" || return 1
  else
    load_physical_context_before "$logical_parent" || return 1
  fi
fi

[ -f "$f/cube-context" ] && source "$f/cube-context"
return 0

}

load_logical_context_after() {

local f=$1 
local logical_parent=${f%/*}
local physical_parent=$(realpath "$logical_parent")

[ -f "$f/cube-context-after" ] && source "$f/cube-context-after"
[ -d "$f/handlers" ] && handler_folders+=( "$f/handlers" )

if [ "${#logical_parent}" -gt 1 ]; then
  if [ "$physical_parent" != "$logical_parent" ]; then
    load_logical_context_after "$physical_parent" || return 1
    load_physical_context_after "$physical_parent" || return 1
  else
    load_physical_context_after "$logical_parent" || return 1
  fi
fi

return 0

}

