#!/bin/bash

SIMPLETON_EXTENSIONS=${SIMPLETON_EXTENSIONS:-$SIMPLETON_REPO/..}

# don't let other users read any files written by these scripts
umask 0077

# current_cube must be set before this is used
alias init_and_load_context_a='
  local dimensions=( )
  init_context "$current_cube" || fail
  eval "$localize_dim_vars"
  load_context "$current_cube" || fail
'

# this must be done after dim is updated
# this probably isn't needed, since we do normalization as part of dim update
alias normalize_dims_a='
  if ! normalize_dimensions "$current_cube"; then
    trace 5 "Dimension normalization failed. One of the dimensions must be invalid."
    fail
  fi
'

init_context() {

  local current_cube=$1 dimension dimension_folder dimension_plural high_volume=f \
    cell_locks=t cell_logs=f

  # this var should be used by the calling function to localize dim vars (prevent changes to them 
  #  from altering higher call stack values)
  localize_dim_vars=""
  if [ -d "$current_cube/dimension" ]; then
    for dimension_folder in $(find "$current_cube/dimension" -mindepth 1 -maxdepth 1 -type d); do
      dimension=${dimension_folder##*/}
      dimension_plural=${dimension}s
      localize_dim_vars+="local $dimension $dimension_plural; "
      dimensions+=( $dimension )
    done
  fi

  reset_expand_dim

}

reset_expand_dim() {

  # override this in cubes to support aliases, dimension groups, and defaults
  # should store values in plural form of var, and only plural form should be used after this
  # should fail (return 1) if any values are invalid, or if required value is missing
  expand_dim() {
    local dimension=$1; shift
    local dimension_plural=${dimension_plural}s; shift
    local value=${!dimension_plural:-${!dimension:-}}
    [ -z "$value" ] && return 1
    eval "$dimension_plural=\$value"
    return 0
  }

  # usually this doesn't need to be overridden, since it uses expand_dim to determine if it's valid
  validate_dims() {
    for dim in "${dimensions[@]}"; do
      if ! expand_dim "$dim"; then
        return 1
      fi
    done
    return 0
  }

}

normalize_dimensions() {
trace -5 "Normalizing dimensions"
begin_function

  local dimension current_cube=$1 value dimension_plural dimension_folder
  dimensions=( )
  if [ -d "$current_cube/dimension" ]; then
    begin_for dimension_folder in $(find "$current_cube/dimension" -mindepth 1 -maxdepth 1 -type d); doo
      dimension=${dimension_folder##*/}
      dimension_plural=${dimension}s
      value=${!dimension_plural:-${!dimension:-}}
      expand_dimension "$dimension_folder" "$dimension_plural" "$value" || fail
    end_for
  fi

end_function
handle_return
}

load_context() {
local f=$1 
local parent=${f%/*}
[ "${#parent}" -gt 1 ] && { load_context_before "$parent" || return 1; }
[ -f "$f/cube-context" ] && source "$f/cube-context"
[ -f "$f/cube-context-after" ] && source "$f/cube-context-after"
[ "${#parent}" -gt 1 ] && { load_context_after "$parent" || return 1; }
return 0
}

load_context_before() {
local f=$1 
local parent=${f%/*}
[ "${#parent}" -gt 1 ] && { load_context_before "$parent" || return 1; }
[ -f "$f/cube-context" ] && source "$f/cube-context"
return 0
}

load_context_after() {
local f=$1 
local parent=${f%/*}
[ -f "$f/cube-context-after" ] && source "$f/cube-context-after"
[ "${#parent}" -gt 1 ] && { load_context_after "$parent" || return 1; }
return 0
}

decrypt_file() {

local from=$1; shift
local to=$1; shift

trace 0 "Decrypting $from"
begin_function

  mkdir -p "$tmp_path" || fail

  if [ ! -f "$current_cube/key/key.$USER" ]; then
    err "You don't have a key for this cube ($USER). Ask someone who does to add you. Existing keys:" 
    find $current_cube/key -name "key.*" >&2
    fail
  fi

  # extract the master key
  openssl pkeyutl -decrypt -inkey ~/.ssh/id_rsa -in "$current_cube/key/key.$USER" -out $tmp_path/master || {
    err "Failed to decrypt master key." 
    fail
  }

  # decrypt the secret file
  openssl enc -aes256 -in $from -out $to -d -pass file:$tmp_path/master || {
    err "Failed to decrypt secret file." 
    fail
  }

end_function
handle_return

}

