#!/bin/bash

type -t cube_add >/dev/null && return 0

cube_add() {

local subject=$1              # which cube
local use_id=${use_id:-f}     # whether the cube part is cell specific or not
local part=${part}            # which cube part to add to
local values=${values}        # which values to add

trace 0 "Adding part $part to cube ${subject#$PWD} with values=[$values]"
begin_function
  
  case $part in
    dim)
      source $SIMPLETON_REPO/lib/cell-new || fail
      local v
      begin_for v in $values; doo
        type=dim cube_new $subject/dim/$v || fail
      end_for
      ;;
    *)
      err "Unknown cube part: $part"
      fail
      ;;
  esac

end_function
handle_return

}
