#!/bin/bash

archetype_folders="$SIMPLETON_REPO/archetypes"

cube_new() {

local subject=$1
local type=${type:-standard}

trace 0 "Creating new cell $subject of type $type"
begin_function

  mkdir -p $subject || fail

  local type_folder=
  begin_for f in $archetype_folders; doo
    if [[ -d $f/$type ]]; then
      type_folder=$f/$type
      break
    fi
  end_for

  if [[ ! "$type_folder" ]]; then
    err "Couldn't find archetype for type $type in $archetype_folders"
    fail
  fi

  rsync -auq $type_folder/ $subject/ || fail

end_function
handle_return

}
