#!/bin/bash

SIMPLETON_EXTENSIONS=${SIMPLETON_EXTENSIONS:-$SIMPLETON_REPO/..}

# don't let other users read any files written by these scripts
umask 0077

# params: subject
# output: cube
get_cube() {
local subject=$1
cube=
while [[ ${#subject} -gt 1 && $subject =~ / ]]; do
  if [[ -f "$subject/cube-context" ]]; then
    cube=$subject
    break
  fi
  subject=${subject%/*}
done
[[ "$cube" ]]
}

get_tmp_path() {
local current_cube=$1
if [[ -d $current_cube/tmp ]]; then
  tmp_path=$current_cube/tmp
elif [[ -d ~/tmp ]]; then
  tmp_path=~/tmp
else
  tmp_path=/tmp
fi
return 0
}

# inputs: from to tmp_path current_cube
# will write output to file at $to
decrypt_file() {

local from=$from
local to=$to
local tmp_path=$tmp_path
local current_cube=$current_cube
local user_private_key=${user_private_key:-~/.ssh/id_rsa}

trace $log_trace "Decrypting $from to $to"
begin_function

  if [[ ! -f "$user_private_key" ]]; then
    err "Private key is missing. Set path to it with user_private_key env var, or put it here: $user_private_key"
    err "You may create one using: ssh-keygen -mPEM"
    fail1
  fi

  if [[ ! "$tmp_path" ]]; then
    err "tmp_path must be set to a directory before calling decrypt_file."
    fail1
  fi

  if [[ ! -d $tmp_path ]]; then
    mkdir -p $tmp_path || fail
  fi

  if [[ ! -d "$current_cube" ]]; then
    err "current_cube must be set before calling decrypt_file"
    fail1
  fi

  if [[ ! -d $current_cube/key ]]; then
    mkdir $current_cube/key || fail
  fi

  if [[ ! -f "$current_cube/key/key.$USER" ]]; then
    err "You don't have a key for this cube ($USER). Ask someone who does to add you. Existing keys:" 
    find -L $current_cube/key -name "key.*" >&2
    fail1
  fi

  # extract the main key
  if ! openssl pkeyutl -decrypt -inkey $user_private_key -in "$current_cube/key/key.$USER" -out $tmp_path/main; then
    err "Failed to decrypt main key." 
    fail1
  fi
  defer "rm $tmp_path/main"

  # decrypt the secret file
  if ! openssl enc -aes256 -pbkdf2 -in $from -out $to -d -pass file:$tmp_path/main; then 
    err "Failed to decrypt secret file." 
    fail1
  fi

end_function
handle_return

}

encrypt_file() {

local from=$from
local to=$to
local tmp_path=$tmp_path
local current_cube=$current_cube
local user_private_key=${user_private_key:-~/.ssh/id_rsa}

trace $log_trace "Encrypting $from to $to"
begin_function

  if [[ ! -f "$user_private_key" ]]; then
    err "Private key is missing. Set path to it with user_private_key env var, or put it here: $user_private_key"
    err "You may create one using: ssh-keygen -mPEM"
    fail1
  fi

  if [[ ! "$tmp_path" ]]; then
    err "tmp_path must be set to a directory before calling decrypt_file."
    fail1
  fi

  if [[ ! -d $tmp_path ]]; then
    mkdir -p $tmp_path || fail
  fi

  if [[ ! -d "$current_cube" ]]; then
    err "current_cube must be set before calling decrypt_file"
    fail1
  fi

  if [[ ! -d $current_cube/key ]]; then
    mkdir $current_cube/key || fail
  fi

  if [[ ! -f "$current_cube/key/key.$USER" ]]; then

    local key_count=$(find -L $current_cube/key -mindepth 1 -maxdepth 1 -name 'key.*' -type f | wc -l)

    if [[ $key_count -gt 0 ]]; then

      err "You don't have a key for this cube ($USER). Ask someone who does to add you. Existing keys:" 
      find -L $current_cube/key -name "key.*" >&2
      fail1

    else

      trace $log_info "There are no keys for this cube yet. Will create a new key."

      # create a new main key
      if ! openssl rand -base64 40 >$tmp_path/main; then
        err "Failed to generate new main key."
        fail1
      fi
      defer "rm $tmp_path/main"

      # create a compatible public key from the user's private key
      if ! openssl pkey -in $user_private_key -out $tmp_path/public -pubout; then 
        err "Failed to convert private key to public key."
        fail1
      fi

      # encrypt main key with given user key
      if ! openssl pkeyutl -encrypt -pubin -inkey $tmp_path/public -in $tmp_path/main -out $current_cube/key/key.$USER; then
        err "Failed to encrypt main key."
        fail1
      fi

    fi
  else 
    # extract the main key
    if ! openssl pkeyutl -decrypt -inkey $user_private_key -in $current_cube/key/key.$USER -out $tmp_path/main; then
      err "Failed to decrypt main key." 
      fail1
    fi

    defer "rm $tmp_path/main"
  fi
    
  # encrypt the file with main key
  if ! openssl enc -aes256 -pbkdf2 -in $from -out $to -pass file:$tmp_path/main; then
    err "Failed to create new secret file."
    fail1
  fi

end_function
handle_return

}

