#!/usr/bin/env bash

type -t clean_lib_loaded >/dev/null && return 0
clean_lib_loaded=t

clean_cell_remove_trunk_context() {
  if [[ "$cell_path" != "$trunk_cell" && -e $trunk_cell/.cyto/context-trunk ]]; then
    rm $trunk_cell/.cyto/context-trunk || return 1
  fi
  return 0
}

clean_derive_caches() {
  local current_path=$1
  if [[ -f $current_path/.lib/derive-cache ]]; then
    rm $current_path/.lib/derive-cache || return 1
  fi
  if [[ -f $current_path/.lib/dim-cache ]]; then
    rm $current_path/.lib/dim-cache || return 1
  fi
  local parent=${current_path%/*}
  if [[ $parent == /*/* ]]; then
    clean_derive_caches $parent || return 1
  fi
}

clean_cell() {
  local cell_path=$1
  local clean_depth=${clean_depth:-1}
  local clean_parent_cells=${clean_parent_cells:-t}

  begin_function

    if [[ $clean_parent_cells == t ]]; then
      local parent=${cell_path%/*}
      begin_while [[ $parent == /*/*/*:* ]]; doo
        if [[ -d $parent/.dna ]]; then
          clean_parent_cells=f kind=context clean_cell $parent || fail
        fi
        parent=${parent%/*}
      end_while
    fi

    (( clean_depth-- ))
    if (( clean_depth > 0 )) && [[ -d $cell_path/.cyto/up ]]; then
      local upstreams=$(find1 $cell_path/.cyto/up -type d | sort -g)
      local up
      begin_for up in $upstreams; doo
        local up_cell=$up/chosen
        if [[ -d $up_cell ]]; then
          up_cell=$(readlink $up_cell)
          clean_cell $up_cell || fail
        else
          local choices=$(find1 $up/choices -type d | sort -g)
          local choice
          begin_for choice in $choices; doo
            clean_cell $choice || fail
          end_for
        fi
      end_for
    fi

    load_branch_info $cell_path || fail
    get_short_cell
    log_info "Cleaning $short_cell..." 

    local clean_file=$cell_path/.dna/clean_op.fun
    if [[ -f $clean_file ]]; then
      local make_or_load=load
      make_or_load_dna_item $clean_file || fail
      clean_op || fail
    fi

    local clean_resist=$cell_path/.dna/resist_clean.var
    if [[ -f $clean_resist && ${top_level_clean:-t} == f ]]; then
      log_warn "Skipping $short_cell since it's clean resistant"
      break
    else
      log_info "Cleaning"
    fi

    local x
    case $kind in
      all)
        begin_for x in $cell_path/!(.*) $cell_path/.cyto; doo
          log_debug "Removing ${x#$cell_path/}"
          rm -rf $x &>/dev/null
        end_for
        clean_cell_remove_trunk_context || fail
        clean_derive_caches $cell_path || fail
      ;;
      co*)
        if [[ -d $cell_path/.cyto ]]; then
          local context_files
          context_files=$(find1 $cell_path/.cyto -name "context*") || fail
          if [[ "$context_files" ]]; then
            rm $cell_path/.cyto/context* || fail
          fi
        fi
        clean_cell_remove_trunk_context || fail
      ;;
      cy*)
        if [[ -e $cell_path/.cyto ]]; then
          rm -rf $cell_path/.cyto || fail
        fi
        clean_cell_remove_trunk_context || fail
      ;;
      da*)
        begin_for x in $(find1 $cell_path -not -name '.*' -not -name '*:*'); doo
          log_verbose "Removing ${x#$cell_path/}"
          rm -rf $x &>/dev/null
        end_for
        if [[ -f $cell_path/.cyto/status/up-to-date ]]; then
          rm $cell_path/.cyto/status/up-to-date
        fi
      ;;
      de*)
        clean_derive_caches $cell_path || fail
      ;;
      b*)
        begin_for x in $(find1 $cell_path -type d -not -name '.*' -name '*:*'); doo
          if [[ "$x" != *:* ]]; then
            continue
          fi
          log_verbose "Removing ${x#$cell_path/}"
          rm -rf $x &>/dev/null
        end_for
        if [[ -f $cell_path/.cyto/status/up-to-date ]]; then
          rm $cell_path/.cyto/status/up-to-date
        fi
      ;;
      i*)
        if [[ -f $cell_path/.cyto/status/up-to-date ]]; then
          rm $cell_path/.cyto/status/up-to-date
        fi
      ;;
      *)
        log_fatal "Invalid clean kind ($kind). Must be one of: all, branches, context, cyto, data, derive-caches, invalidate"
        fail1
      ;;
    esac

  end_function
  handle_return
}

clean_folder() {
  local folder=$1
  begin_function

    if [[ -e "$folder/.dna" ]]; then
      clean_cell $folder || fail
    fi

    local folders
    folders=$(find1 $folder -type d -not -name '.*') || fail
    begin_for folder in $folders; doo
      top_level_clean=f \
      clean_parent_cells=f clean_folder $folder || fail
    end_for

  end_function
  handle_return
}

