#!/bin/bash

type -t cube_add >/dev/null && return 0

dna_add() {

local subject=$1              # which cube
local use_id=${use_id:-f}     # whether the cube part is cell specific or not
local part=${part}            # which cube part to add to
local values=${values}        # which values to add

local cube=${subject#$PWD}
if [[ ! "$cube" ]]; then
  cube=${subject##*/work/}
fi

trace 0 "Adding values [$values] to part $part of cube $cube"
begin_function
  
  case $part in
    dim)
      source $SIMPLETON_REPO/lib/dna-new || fail
      local v
      begin_for v in $values; doo
        type=dim dna_new $subject/dim/$v || fail
      end_for
      ;;
    up)
      source $SIMPLETON_REPO/lib/dna-link || fail
      local v
      begin_for v in $values; doo
        mkdir -p $subject/up || fail
        dna_link $v $subject/up/ || fail
        mkdir -p $v/down || fail
        dna_link $subject $v/down/ || fail
      end_for
      ;;
    *)
      err "Unknown cube part: $part"
      fail
      ;;
  esac

end_function
handle_return

}
