#!/bin/bash

type -t dna_link >/dev/null && return 0

dna_link() {

local from=$1; shift
local to=$1

if [[ ! -f $from/cube-context ]]; then
  err "Source cube is invalid: $from"
  err "Either it is not a cube, or the folder doesn't exist"
  return 1
fi

trace 0 "Linking cell ${from##*/work/} to ${to##*/work/}"
begin_function

  if [[ ${to} != ${to%/} ]]; then
    to=$to${from##*/}
  fi

  if [[ -e $to || -L $to ]]; then
    if [[ ${force:-f} == t ]]; then
      maybe rm -r $to || fail
    else
      err "Target cube already exists or a folder or link is already there."
      err "Delete it if you want to create it again"
      fail1
    fi
  fi

  local abs_from=$(realpath -L $from)
  maybe ln -s $abs_from $to || fail

end_function
handle_return

}
