#!/bin/bash

type -t dna_new >/dev/null && return 0

get_archetype_folders() {
archetype_folders="$SIMPLETON_REPO/archetypes"
}

dna_new() {

local subject=$1
local type=${type:-standard}

if [[ "$subject" == "$PWD" || -d "$subject" ]]; then
  err "You must specify a target cube path to create, which does not already exist."
  return 1
fi

trace 0 "Creating new cell ${subject#$PWD/} of type $type"
begin_function

  mkdir -p $subject || fail
  get_archetype_folders || fail

  local type_folder=
  begin_for f in $archetype_folders; doo
    if [[ -d $f/$type ]]; then
      type_folder=$f/$type
      break
    fi
  end_for

  if [[ ! "$type_folder" ]]; then
    err "Couldn't find archetype for type $type in $archetype_folders"
    fail
  fi

  rsync -auq $type_folder/ $subject/ || fail

end_function
handle_return

}
