#!/bin/bash

type -t dna_clone >/dev/null && return 0

dna_clone() {

local from=$1; shift
local to=$1

if [[ ${to} != ${to%/} ]]; then
  to=$to${from##*/}
fi

local real_from=$(realpath $from)
to=$(realpath $to)

trace $log_info "Cloning cell ${real_from##*/work/} to ${to##*/work/}"
begin_function

  if [[ -L $from ]]; then
    err "From cell ($from) is a link. It doesn't make sense to use this command on a link."
    err "Just use the cp command for this."
    fail1
  fi

  if [[ ! -f $from/cube-context ]]; then
    err "Source cube is invalid: $from"
    err "Either it is not a cube, or the folder doesn't exist"
    fail1
  fi

  if [[ -e $to ]]; then
    err "Target already exists: $to"
    fail1
  fi

  local f
  maybe mkdir $to || fail
  begin_for f in $(find1 $from); doo
    case ${f#$from/} in
      lock|log|out|status|down|cell)
        trace $log_trace "Skipping $f"
      ;; 
      up)
        maybe mkdir $to/up || fail
        local dep to_name=${to##*/}
        # TODO handle multipath deps also
        begin_for dep in $(find1 $from/up); doo
          if [[ -e $dep/down/$to_name ]]; then
            err "$dep/down/$to_name already exists"
            fail1
          fi
          if [[ -e $to/up/${dep##*/} ]]; then
            err "$to/up/${dep##*/} already exists"
            fail1
          fi
          maybe cp -a $dep $to/up/ || fail
          maybe ln -s $to $dep/down/$to_name || fail
        end_for
      ;;
      *)
        maybe cp -a $f $to/ || fail
      ;;
    esac
  end_for

end_function
handle_return

}
