#!/bin/bash

type -t dna_link >/dev/null && return 0

dna_link() {

local from=$1; shift
local to=$1

trace 0 "Linking cell $from to $to"
begin_function

  if [[ ! -f $from/cube-context ]]; then
    err "Source cube is invalid: $from"
    err "Either it is not a cube, or the folder doesn't exist"
    fail
  fi

  if [[ -e $to || -L $to ]]; then
    err "Target cube already exists or a folder or link is already there."
    err "Delete it if you want to create it again"
    fail
  fi

  ln -s $(realpath --relative-to=${to%/*} $from) $to || fail

end_function
handle_return

}
