#!/bin/bash

# usage: execute {subject}
#   executes the given subject, which is a full path to a folder
execute() {

local subject=$1
local lock_timeout=${lock_timeout:-0}

trace 0 "Executing subject: $small_subject"

begin_function

local subject_folder subject_type
get_subject_type || fail

trace -5 "Sourcing context files"
init_context || fail
load_context "$subject_folder" || fail

deal_with || fail

trace 0 "Subject executed successfully"

end_function
handle_return

}

get_subject_type() {
begin_function
subject_type=folder
subject_folder=$subject
if [ ! -d "$subject" ]; then
  subject_folder="${subject%/*}"
  if  [ ! -d "$subject_folder" ]; then
    err "Subject doesn't exist: $small_subject"
    fail
  else
    if [ -f "$subject" ]; then
      subject_type=file
    else
      subject_type=implicit
    fi
  fi
fi
end_function
handle_return
}

deal_with() {

local handler_to_try handler_path_to_try handler_found handler_name
trace 0 "Figuring out what to do with $subject"

begin_function

if [ $subject_type == folder ]; then

  trace -5 "Checking if subject needs to be executed"
  is_refresh_needed "$subject" || fail
  if [ $refresh_needed == f ]; then
    trace 0 "Refresh is not needed"
    succeed
  else
    trace 0 "Refresh is needed"
  fi

fi

find_handler "$subject" || fail

if [ "$handler_found" ]; then

  if [ $subject_type == folder ]; then
    lock "$subject_meta/lock" $lock_timeout || fail
    touch "$subject_meta/last-run-began" || fail
    mkdir -p "$subject_out" || fail
    mkdir -p "$subject_log" || fail
    mkdir -p "$subject_meta" || fail
  fi

  trace -5 "Executing handler $handler_found"
  source "$handler_found" || fail

  [ $subject_type == folder ] && tee_output_to "$subject_log/log-current"

  local handler_failed=f
  handle "$subject" || handler_failed=t

  if [ $subject_type == folder ]; then
    untee_output
    touch "$subject_meta/last-run-ended" || fail
    unlock "$subject_meta/lock"
    if [ "$handler_failed" == f ]; then
      touch -r "$subject_meta/last-run-began" "$subject_meta/last-success-began" || fail
      mv "$subject_log/log-current" "$subject_log/log-last-error"
      ln -s "$subject_log/log-last-error" "$subject_log/log-previous"
    else
      mv "$subject_log/log-current" "$subject_log/log-last-success"
      ln -s "$subject_log/log-last-success" "$subject_log/log-previous"
    fi
  fi

else # no handler found
  if [ -d "$subject" ]; then
    trace 0 "Processing contents of $subject folder"
    local f
    begin_for f in $(find "$subject" -mindepth 1 -maxdepth 1 -not -name ".*" | sort); doo
      execute "$f" || fail
    end_for
  else
    trace -5 "Ignoring file $subject"
  fi
fi

end_function
handle_return

}

find_handler() {
local file_or_folder=$1
local file_or_folder_base=${file_or_folder##*/}
handler_found=
for handler_path_to_try in "${handler_path[@]}"; do
  for handler_to_try in $(find "${handler_path_to_try}" -mindepth 1 -maxdepth 1 -not -name ".*" -type f); do
    handler_name=${handler_to_try##*/}
    if [ "${file_or_folder_base%$handler_name}" != "$file_or_folder_base" ]; then
      handler_found=$handler_to_try
      trace -5 "Handler found: $handler_found"
      break 2
    fi
  done
done
}

get_handler_path() {
if [ ! "$handler_path" ]; then
  handler_path=( )
  local remaining_path=$subject h
  while [ "${#remaining_path}" -gt 1 ]; do
    h="$remaining_path/handlers"
    if [ -d "$h" ]; then
      handler_path+=( "$h" )
    fi
    remaining_path=${remaining_path%/*}
  done
  handler_path+=( $SIMPLETON_REPO/handlers )
fi
}

is_refresh_needed() {
local subject=$1

if [ ! -d "$subject" ]; then
  refresh_needed=t
  return 0
fi

if [ ! -e "$subject_meta/last-success-began" ]; then 
  refresh_needed=t
  return 0
fi

local newer_file_found=$(
  find "$subject_folder" -mindepth 1 \
    -not -name out -not -name meta -not -name log -not -name .git \
    -newer "$subject_meta/last-success-began" -print -quit
  )
if [ "$newer_file_found" ]; then 
  trace -5 "Found file that is newer than out: $newer_file_found"
  refresh_needed=t
  return 0
fi

is_subject_fresh "$subject_folder" || return 1
if [ $subject_fresh == f ]; then
  trace -5 "Subject is not fresh enough"
  refresh_needed=t
  return 0
fi

refresh_needed=f
return 0
}

# Intended to be overridden by subjects which have live external dependencies
is_subject_fresh() {
subject_fresh=t
}

tee_output_to() {
local target=$1
exec 1> >(tee "$target")
exec 2> >(tee -a "$target")
exec ${fd_trace}> >(tee -a "$target")
}

untee_output() {
exec 1>&$fd_original_out
exec 2>&$fd_original_err
exec $fd_trace>&$fd_original_trace
}
