#!/bin/bash

# usage: execute {target}
#   executes the given target, which is a full path to a folder
execute() {

local target=$1
if [ ! "$target" ]; then
  target=$PWD
fi

trace "Executing target: $target"

begin_function

if [ ! -d "$target" ]; then
  err "Target doesn't exist, or isn't a directory: $target"
  fail
fi

if [ ! "$handler_path" ]; then
  handler_path=( )
  local remaining_path=$target
  begin_while [ "${#remaining_path}" -gt 1 ]; doo
    local h="$remaining_path/.simpleton/handlers"
    if [ -d "$h" ]; then
      handler_path+=( "$h" )
    fi
    remaining_path=${remaining_path%/*}
  end_while
  handler_path+=( $SIMPLETON_HOME/handlers )
fi

local file_or_folder handler_to_try handler_path_to_try handler_found handler_name
begin_for file_or_folder in $(find "$target" -mindepth 1 -maxdepth 1 -not -name ".*" | sort); doo

  handler_found=

  begin_for handler_path_to_try in "${handler_path[@]}"; doo
    begin_for handler_to_try in $(find "${handler_path_to_try}" -mindepth 1 -maxdepth 1 -not -name ".*" -type f); doo
      handler_name=${handler_to_try##*/}
      if [ "${file_or_folder%$handler_name}" != "$file_or_folder" ]; then
        handler_found=$handler_to_try
        break 2
      fi
    end_for
  end_for

  if [ "$handler_found" ]; then
  else
  fi

end_for

end_function
handle_return

}