#!/bin/bash

# some required defaults
tmp_folder="${tmp_folder:-/tmp}"
trace=${trace:-5}
importance=${importance:-0}
trace_indent=${trace_indent:-f}
trace_max=$trace
trace_force=${trace_force:-f}
bash_trace=${bash_trace:-100}

# usage example:
#   do_stuff() {
#     begin_function
#       open_connection || fail
#       begin_for ((i = 0; i < 10; i++)); doo
#         stuff || fail
#       end_for
#      
#       more_stuff
#     end_function
#     close_connection
#     handle_return
#   }

if [ $trace -gt $bash_trace ]; then
  alias begin_function='let trace--; [ $trace -lt $bash_trace ] && set +x || set -x; local return_value=0; while true; do'
  alias    begin_while='let trace--; [ $trace -lt $bash_trace ] && set +x || set -x;       return_value=0; while'
  alias      begin_for='let trace--; [ $trace -lt $bash_trace ] && set +x || set -x;       return_value=0; for'
  alias   end_function='break; done; [ $trace -ge $bash_trace ] && set -x; let trace++'
  alias      end_while='       done; [ $trace -ge $bash_trace ] && set -x; let trace++; [ $return_value != 0 ] && break'
  alias        end_for='       done; [ $trace -ge $bash_trace ] && set -x; let trace++; [ $return_value != 0 ] && break'
else
  alias begin_function='let trace--; local return_value=0; while true; do'
  alias    begin_while='let trace--; return_value=0; while'
  alias      begin_for='let trace--; return_value=0; for'
  alias   end_function='break; done; let trace++'
  alias      end_while='       done; let trace++; [ $return_value != 0 ] && break'
  alias        end_for='       done; let trace++; [ $return_value != 0 ] && break'
fi

# to avoid bash syntax parsing problems
alias doo='do'

alias fail='{ return_value=1; break; }'
alias failed='[ $return_value -gt 0 ]'
alias succeed='{ return_value=0; break; }'
alias succeeded='[ $return_value -eq 0 ]'

# should be at the end of every function which contains a try / end_try block
alias handle_return='return $return_value'
alias handle_exit='exit $return_value'

# make sure we clean up after ourselves whether we've launched a background job or allocated resources
trap 'trace_indent=f trace -5 "Cleaning up"; 
  { kill $(jobs -p) && wait; } 2>/dev/null || true; 
  eval "${cleanup_on_exit:-}"' EXIT

NL=$'\n'
TAB=$'\t'

   LIGHT_RED=$'\033[0;31m'
         RED=$'\033[1;31m'
 LIGHT_GREEN=$'\033[0;32m'
       GREEN=$'\033[1;32m'
LIGHT_YELLOW=$'\033[0;33m'
      YELLOW=$'\033[1;33m'
  LIGHT_BLUE=$'\033[0;34m'
        BLUE=$'\033[1;34m'
LIGHT_PURPLE=$'\033[0;35m'
      PURPLE=$'\033[1;35m'
  LIGHT_CYAN=$'\033[0;36m'
        CYAN=$'\033[1;36m'
 LIGHT_WHITE=$'\033[0;37m'
       WHITE=$'\033[1;37m'
 LIGHT_BLACK=$'\033[0;38m'
       BLACK=$'\033[1;38m'
       RESET=$'\033[0m'
  CLEAR_LINE=$'\033[2K\r'
       CLEAR=$'\033[2J'
CLEAR_SCREEN=$'\033[2J\r\033[H'
   CURSOR_UP=$'\033[1A'
     REVERSE=$'\033[7m'

COL10=$'\n\e[A\e[10G'
COL20=$'\n\e[A\e[20G'
COL30=$'\n\e[A\e[30G'
COL40=$'\n\e[A\e[40G'
COL50=$'\n\e[A\e[50G'
COL60=$'\n\e[A\e[60G'
COL70=$'\n\e[A\e[70G'
COL80=$'\n\e[A\e[80G'
COL90=$'\n\e[A\e[90G'
COL100=$'\n\e[A\e[100G'
COL110=$'\n\e[A\e[110G'
COL120=$'\n\e[A\e[120G'
COL130=$'\n\e[A\e[130G'
COL140=$'\n\e[A\e[140G'
COL150=$'\n\e[A\e[150G'
COL160=$'\n\e[A\e[160G'
COL170=$'\n\e[A\e[170G'
COL180=$'\n\e[A\e[180G'
COL190=$'\n\e[A\e[190G'
COL200=$'\n\e[A\e[200G'

hydrate_template() {
if [[ "$line" =~ \$ ]]; then
  line="${line//\"/\\\"}"
  eval "echo \"$line\"" || return 1
else
  echo "$line"
fi
}

stack_trace() {
local start_frame=${start_frame:-1}
set +x
local count=${#FUNCNAME[*]}
local p n

if [ ${tracing_midline:-f} == t ]; then
  tracing_midline=f
  echo >&$fd_trace
fi

echo "Stack trace:" >&$fd_original_err
for ((n = start_frame; n < count; n++)) ; do
  p=$((n - 1))
  echo "  ${BASH_SOURCE[$n]} ${FUNCNAME[$n]} ${BASH_LINENO[$p]}" >&2
done
}

# put these in front of function calls to increase or decreasing importance of their logs
# ex: verbose do_something_I_want_to_debug "Input1" "Input2"
alias verbose='importance=$((importance+10))'
alias terse='importance=$((importance-10))'

# write output to standard error
#   can be overridden to provide a different behavior
err() {
  local flags=
  if [ "$1" == -n ]; then
    flags=-n
    shift
  fi

  if [ ${tracing_midline:-f} == t ]; then
    tracing_midline=f
    echo >&$fd_trace
  fi

  if [ ${trace_indent:-f} == t ]; then
    [ $trace -gt $trace_max ] && trace_max=$trace
    local pad_size=$((trace_max-trace))
    printf "%${pad_size}s" >&2
  fi

  echo $flags "${RED:-}ERROR: $1${RESET:-}" >&2
}

warn() {
  local flags=
  if [ "$1" == -n ]; then
    flags=-n
    shift
  fi

  if [ ${tracing_midline:-f} == t ]; then
    tracing_midline=f
    echo >&$fd_trace
  fi

  if [ ${trace_indent:-f} == t ]; then
    [ $trace -gt $trace_max ] && trace_max=$trace
    local pad_size=$((trace_max-trace))
    printf "%${pad_size}s" >&2
  fi

  echo $flags "${YELLOW:-}WARNING: $1${RESET:-}" >&2
}

# are we tracing in the middle of a line, or are we at the beginning of a new line?
tracing_midline=f

# use this to log based on current trace level
# usage: trace [-a] [-n] {importance} {string to output}
#   -a uses echo_align to align columns
#   -n skips newline at end
trace() {
  local nonewline=f
  local align=f
  while true; do
    case "$1" in
      -a)
        align=t
        ;;
      -n)
        nonewline=t
        ;;
      *)
        break
        ;;
    esac
    shift
  done

  local importance=${importance:-0}
  let importance+=$1; shift

  if [ $((trace+importance)) -gt 0 -o $trace_force == t ]; then
    if [ $nonewline == t ]; then
      if [ $tracing_midline == f ]; then
        if [ ${trace_debug:-f} == t ]; then
          local pad_size=$((trace_max-trace))
          printf "%3d " $((pad_size+1)) >&$fd_trace
        elif [ $trace_indent == t ]; then
          local pad_size=$((trace_max-trace))
          printf "%${pad_size}s" >&$fd_trace
        fi
        tracing_midline=t
      fi
      if [ $align == t ]; then
        echo_align -n >&$fd_trace "$@"
      else
        echo -n >&$fd_trace "$@"
      fi
    else
      if [ $tracing_midline == t ]; then
        echo >&$fd_trace
        tracing_midline=f
      fi
      if [ ${trace_debug:-f} == t ]; then
        local pad_size=$((trace_max-trace))
        printf "%3d " $((pad_size+1)) >&$fd_trace
      elif [ $trace_indent == t ]; then
        local pad_size=$((trace_max-trace))
        printf "%${pad_size}s" >&$fd_trace
      fi
      if [ $align == t ]; then
        echo_align >&$fd_trace "$@"
      else
        echo >&$fd_trace "$@"
      fi
    fi
  fi

  return 0
}

out() {
  if [ ${tracing_midline:-f} == t ]; then
    tracing_midline=f
    echo >&$fd_trace
  fi
  echo "$@"
}

incomplete() {
  if [ ${tracing_midline:-f} == t ]; then
    tracing_midline=f
    echo >&$fd_trace
  fi
  if [ "$1" ]; then
    echo "Not implemented yet: ${1:-}" >&2
  else
    echo "Not implemented yet." >&2
  fi
  stack_trace
  exit 1
}

# usage: lock {lock name} [{max time in seconds to wait for lock}]
# if timeout is not given, then attempt will immediately fail if it can't get the lock right away
#   otherwise it will keep trying until the timeout is reached or the lock is obtained.
lock() {

local lockfile=$1; shift
local timeout=${1:-0}

trace 0 "Attempting to obtain lock for $lockfile"
begin_function
  if [ -d "$lockfile" ]; then
    trace 0 "Lock folder exists already: $lockfile"
    pid=$(<$lockfile/pid)
    if [ "$pid" == $$ ]; then
      # this process already owns the lock
      trace 0 "This process already owns the lock, so we are done."
      succeed
    fi

    # check to see if the process is still running
    if [ ! "$pid" ] || ! ps $pid &>/dev/null; then
      rm -rf "$lockfile" || fail
      trace 0 "Removed stale lockfile: $lockfile with pid: $pid"
    fi
  fi

  local timeleft=$timeout
  local success=f

  begin_while true; doo

    mkdir "$lockfile" &>/dev/null && success=t
    if [ $success == t ]; then
      echo $$ >$lockfile/pid
      eval "cleanup_on_exit+='rm -rf \"${lockfile}\" &>/dev/null || true;'"
      succeed
    fi

    sleep 1

    timeleft=$((timeleft-1))
    if [ $timeout -gt 0 ] && [ $timeleft -lt 0 ]; then
      trace 0 "Timeout reached. Couldn't obtain the lock in time."
      fail
    fi

  end_while

end_function

if succeeded; then
  trace 0 "Succeeded in obtaining lock"
else
  trace 5 "Failed to obtain lock"
fi

handle_return

}

# usage: unlock {lock name}
#   should only be used if this process actually owns this lock
unlock() {
local lockfile=$1
if [ ! "$lockfile" ]; then
  err "Usage: unlock {lock name}"
  exit 1
fi

rm -rf "$lockfile"
}

# usage: random {p=number of possibilities}
#   sets r={random number between 0 and p-1}
#   it will be fairly evenly distributed below about 1000, but will become more biased as it gets higher
unset random
random() {
  local p=$1
  r=$((RANDOM % p))
}

# usage: random_sleep {min} {max}
#   will sleep for a random interval between min and max
unset random_sleep
random_sleep() {
  local min=$1; shift
  local max=$1
  random $((max-min))
  sleep $((min+r))
}
split_to_array() {
  local var=$1; shift
  local separator=${1:-$'\n'}

  local OIFS=$IFS
  IFS=$separator
  eval "$var=( \$$var )"

  IFS=$OIFS
}

escape_regex() {
  local var=$1

  eval "$var="'${'"$var"'//\"/\\\"}'
  eval "$var="'${'"$var"'// /\\ }'
  eval "$var="'${'"$var"'//\(/\\\(}'
  eval "$var="'${'"$var"'//)/\\)}'
  eval "$var="'${'"$var"'//\?/\\\?}'
}

# usage: echo " blah   " | trim
trim() {
  tr -d '\n' | sed 's/^[[:space:]]*\(.*\)[[:space:]]*$/\1/'
}

to_lower() {
  tr '[:upper:]' '[:lower:]'
}

to_upper() {
  tr '[:lower:]' '[:upper:]'
}

spaces_to_minus() {
  sed 's/  */-/g'
}

upper_first_char() {
  local string=$1
  local first=${string:0:1}
  first=$(echo -n "$first" | tr '[:lower:]' '[:upper:]')
  echo -n "$first${string:1}"
}

convert_to_seconds() {
  local from=$1; shift
  local to=$1
  case "$from" in
    *s)
      eval "$to=${from%s}"
      ;;
    *m)
      eval "$to=$((${from%m}*60))"
      ;;
    *h)
      eval "$to=$((${from%h}*60*60))"
      ;;
    *d)
      eval "$to=$((${from%d}*24*60*60))"
      ;;
    *w)
      eval "$to=$((${from%w}*7*24*60*60))"
      ;;
    *y)
      eval "$to=$((${from%y}*365*24*60*60))"
      ;;
    *)
      err "Unknown time format, use something like: 4h, 3d, 5m"
      return 1
      ;;
  esac
  return 0
}

# echo_align behaves much like echo, except that it aligns columns based on the maximum size of previous lines
# echo_align_reset # will reset the column sizes
# echo_align -n "somestring" # will print the string but not end the line yet
# you can't combine the flags like -rn
# echo_align "string1" "string2" "string3" # the three strings will be in separate columns, possibly padded with spaces to make them align with the preceeding lines
#
# global vars
#   echo_current_column
#   echo_columns
#   echo_previous_column_size
#
# you can preset column widths like this:
#   echo_columns=( 20 10 40 )

echo_align() {
local output=()
local no_new_line no_new_column silent block=
local append
local rigid=f

while [[ $# -gt 0 ]]; do
  local key="$1"; shift

  case $key in
    -b|--block)
      silent=t
      block=t
    ;;
    -r|--rigid)
      rigid=t
    ;;
    -s|--silent)
      silent=t
    ;;
    -n|--no-new-line)
      no_new_line=t
    ;;
    -N|--no-new-column)
      no_new_column=t
    ;;
    *)
      output+=("$key")
    ;;
  esac
done

if [ ${tracing_tiny:-f} == t ]; then
  tracing_tiny=f
  echo
fi

if [ "$block" ]; then
  echo_block+=( "${output[*]}" )
fi

local column_text column_text_size column_max pad_size pad output_column_count echo_columns_count current_column

echo_current_column=${echo_current_column:-0}
echo_previous_column_size=${echo_previous_column_size:-0}
echo_min_pad=${echo_min_pad:-1}

output_column_count=${#output[*]}
let output_column_count+=echo_current_column

if [ "${echo_columns:-}" ]; then
  echo_columns_count=${#echo_columns[*]}
else
  echo_columns_count=0
fi

[ $echo_columns_count -gt $output_column_count ] && output_column_count=$echo_columns_count

current_column=0
for column_text in "${output[@]:-}"; do
  let current_column++ || true
  # only pad if we aren't the last column
  if [ $current_column -lt $output_column_count -o "$no_new_line" ]; then
    column_max=${echo_columns[$echo_current_column]:-0}
    column_text_size=${#column_text}
    let column_text_size+=echo_previous_column_size || true

    if [[ $column_text_size -gt $column_max ]]; then
      column_max=$column_text_size
      pad_size=$echo_min_pad

      if [ $rigid == f ]; then
        echo_columns[$echo_current_column]=$column_max
      fi
      [ "${echo_debug:-}" ] && echo_debug
    else
      let pad_size=column_max-column_text_size+echo_min_pad || true
    fi

    if [ ! "$no_new_column" ]; then
      [ "$pad_size" -le 0 ] && pad_size=$echo_min_pad
      printf -v pad %${pad_size}s
      column_text="${column_text}${pad}"
    fi
  fi
  let echo_current_column++ || true

  [ ! "$silent" ] && echo -n "$column_text"
done

if [ ! "$no_new_line" ]; then
  [ ! "$silent" ] && echo
  echo_current_column=0
fi

if [ "$no_new_column" ]; then
  echo_previous_column_size=$column_text_size
else
  echo_previous_column_size=0
fi

return 0
}

echo_align_reset() {
unset echo_columns
echo_block=( )
echo_current_column=0
}

echo_debug() {
echo
echo "echo_columns=( ${echo_columns[*]:-} )"
echo "echo_current_column=${echo_current_column:-0}"
}

# example: {complex command} | echo_align_stream 
echo_align_stream() {
local line line_array
while IFS= read -r line || [ "${line:-}" ]; do
  line_array=( $line )
  echo_align "${line_array[@]}"
  unset line
done
}

# example: {complex command} | echo_align_block
# will read the whole input at once, and determine alignment, then output it
# this is the opposite of echo_align_stream
echo_align_block() {
local line line_array block=()
while IFS= read -r line || [ "${line:-}" ]; do
  line_array=( $line )
  echo_align -b "${line_array[@]:-}"
  unset line
done

echo_align_dump
}

echo_align_dump() {
for line in "${echo_block[@]:-}"; do
  line_array=( $line )
  echo_align "${line_array[@]:-}"
done
}

######################################################
# BASH Debugger
# Usage: {command} debug=t
# press '?' for list of commands while debugging
######################################################

# make sure that all functions can be stepped through for debugging
set -T

COLUMNS=${COLUMNS:-120}

debug_expansion_clean() {
  cat "$1" | sed -ln '/^+ /p'
}

debug_output_reversed_line() {
  echo -n "$REVERSE" >&$fd_original_err
  local line=$(sed -E -n "${debug_line_num}p;${debug_line_num}q" "$raw_debug_path_to_source_file")
  local pad_size line_length=${#line}
  let pad_size=COLUMNS-line_length
  echo -n "$line" >&$fd_original_err
  printf %${pad_size}s >&$fd_original_err
  echo "$RESET" >&$fd_original_err
}

debug_display_source() {
  local debug_start_line=$((debug_list_offset+debug_line_num))
  local debug_end_line=$((debug_start_line+19))

  if [ $debug_start_line -le $debug_line_num -a $debug_line_num -le $debug_end_line ]; then
    if [ $debug_start_line -lt $debug_line_num ]; then
      sed -n "$debug_start_line,$((debug_line_num-1))p;$((debug_line_num-1))q" "$debug_path_to_source_file" >&$fd_original_err
    fi
    debug_output_reversed_line
    if [ $debug_line_num -lt $debug_end_line ]; then
      sed -n "$((debug_line_num+1)),${debug_end_line}p;${debug_end_line}q" "$debug_path_to_source_file" >&$fd_original_err
    fi
  else
    sed -n "$debug_start_line,${debug_end_line}p;$((debug_end_line))q" "$debug_path_to_source_file" >&$fd_original_err
  fi
}

debug_trap() {
  debug_rewind=f
  local IFS=$'\n'$'\t'" "

  local debug_full_path=${debug_full_path:-f}
  local debug_path_to_source_file=$1; shift
  local debug_source_file=${debug_path_to_source_file##*/}
  local raw_debug_path_to_source_file=$debug_path_to_source_file
  if [ $debug_full_path == t ]; then
    debug_source_file=$debug_path_to_source_file
  fi

  local debug_line_num=$1; shift
  let debug_line_num-=3
  local debug_function=$1; shift
  local debug_command=$1; shift

  local debug_r=-1

  local debug_current_depth=${#FUNCNAME[*]}

  if [ "$debug_search" ]; then
    local fixed_command
    fixed_command=${debug_command}
    fixed_command=${fixed_command//\\\$/\\\\\$}
    fixed_command=${fixed_command//\"/\\\"}
    if [ "$debug_expanded_search" == t ]; then
      set +u
      eval "local expanded_command=\"$fixed_command\""
      set -u
    else
      local expanded_command=
    fi

    if [ $debug_search_deep == t \
       -o $debug_current_depth -le $debug_max_depth ] \
       && [[ " $debug_command " =~ $debug_search \
       || " $expanded_command " =~ $debug_search ]]; then
      debug_search=
      debug_max_depth=$debug_current_depth
    else
      debug_r=0
    fi
  else
    if [ $debug_current_depth -gt $debug_max_depth -a -z "$debug_stop_at" ]; then
      debug_r=0
    fi
  fi

  if [ $debug_step_to_next_line == t -a \
     -z "$debug_stop_at" -a \
     "$raw_debug_path_to_source_file $debug_line_num" == "$debug_last_location" -a \
     $debug_function != none ]; then
    debug_r=0
  fi

  if [ "$debug_stop_at" ]; then
    if [ "$raw_debug_path_to_source_file $debug_line_num" != "$debug_stop_at" ]; then
      debug_r=0
    else
      debug_max_depth=$debug_current_depth
      debug_stop_at=
    fi
  fi

  if [ $debug_step_to_later_line == t \
     -a "$debug_line_num" -le "$debug_prev_line" \
     -a $debug_function != none ]; then
    debug_r=0
  else
    debug_step_to_later_line=f
  fi

  if [ $debug_step_to_next_function == t -a \
     "$debug_function" == "$debug_prev_function" \
     ]; then
    debug_r=0
  fi

  [ $debug_r == 0 ] && return 0

  debug_last_location="$debug_path_to_source_file $debug_line_num"
  debug_prev_line="$debug_line_num"
  debug_prev_function=$debug_function
  debug_step_to_next_function=f

  if [ $debug_highlight == t ]; then

    local previous_dir=$PWD
    debug_path_to_source_file=$(cd "$debug_dir"; cd ${debug_path_to_source_file%/*}; pwd)/${debug_path_to_source_file##*/}
    local highlighted_source=$tmp_folder/debug_highlight/${debug_path_to_source_file#/}
    if [ ! -f "$highlighted_source" ]; then
      mkdir -p "${highlighted_source%/*}"
      #cat "$debug_path_to_source_file" | highlight -S shellscript -O ansi >"$highlighted_source"
      cat "$debug_path_to_source_file" | source-highlight -s bash -f esc >"$highlighted_source"
    fi
    debug_path_to_source_file=$highlighted_source

  fi

  if [ $debug_expansion == 1 -a $debug_long_command == f ] || [ $debug_expansion == 2 ]; then
    if [ -f "$debug_out_path" ]; then
      rm "$debug_fifo_path" &>/dev/null
      cat "$debug_out_path"
      [ "${debug_expansion_pid:-}" ] && kill $debug_expansion_pid
      debug_expansion_pid=
      BASH_XTRACEFD=
    fi
  elif [ -f "$debug_out_path" ]; then
    rm "$debug_out_path"
  fi

  local display_command=$debug_command
  local raw_display_command=$display_command
  if [ $debug_step_to_next_line == t -o $debug_long_command == t ] && [ $debug_function != none ]; then
    display_command=$(sed -E -n "${debug_line_num}{s/^ *(.*)/\\1/;p;q;}" "$debug_path_to_source_file")
    raw_display_command=$(sed -E -n "${debug_line_num}{s/^ *(.*)/\\1/;p;q;}" "$raw_debug_path_to_source_file")
  fi

  local debug_c debug_array
  while [ $debug_r == -1 ]; do

    echo >&$fd_original_err
    set +u
    [ "$debug_watch" ] && eval "echo \"\$debug_watch=[$debug_watch]\"" >&$fd_original_err
    set -u

    echo -n "$RED$debug_source_file $BLUE" >&$fd_original_err
    printf "%4d" $debug_line_num >&$fd_original_err
    echo -n " $GREEN$debug_function $RESET: $display_command" >&$fd_original_err

    debug_long_command=f
    read -s -n1 debug_c <&$fd_original_in

    if [ "$debug_c" != l -a "$debug_c" != L ]; then
      debug_list_offset=0
      debug_list_dir=none
    fi

    if [ "$debug_c" == l -a $debug_list_dir != none ]; then
      echo -n "$CLEAR_LINE" >&$fd_original_err
      echo -n "$CURSOR_UP$CLEAR_LINE" >&$fd_original_err
      if [ "$debug_watch" ]; then
        echo -n "$CURSOR_UP$CLEAR_LINE" >&$fd_original_err
      fi
    else
      echo >&$fd_original_err
    fi

    if [ "$debug_c" == L ]; then
      echo -n "$CLEAR_SCREEN" >&$fd_original_err
    fi

    #if [ $debug_function == none ] && [[ "$debug_c" =~ (c|l|L) ]] ; then
    #  echo "We are outside of a function. Can't display source." >&$fd_original_err
    #else
      case "$debug_c" in
        a)
          read -p "Name of array variable: " debug_array <&$fd_original_in
          set +u
          local i size
          eval "size=\${#${debug_array}[*]}"
          echo "size=$size" >&$fd_original_err
          for ((i=0; i<size; i++)); do
            eval "echo \"$i: \\\"\${$debug_array[$i]}\\\"\"" >&$fd_original_err
          done
          set -u
          ;;
        c)
          echo >&$fd_original_err
          let debug_list_offset=-9
          debug_display_source
          debug_list_dir=forwards
          let debug_list_offset+=20
          ;;
        C)
          echo "Continuing..." >&$fd_original_err
          trap - DEBUG
          debug_r=0
          debug_long_command=t
          ;;
        d)
          read -e -p "Display: " debug_display <&$fd_original_in
          set +u
          eval "echo \"[$debug_display]\"" >&$fd_original_err
          set -u
          ;;
        D)
          set +u
          eval "echo \"[$debug_display]\"" >&$fd_original_err
          set -u
          ;;
        e)
          read -p "Eval: " debug_expression <&$fd_original_in
          set +u
          eval "$debug_expression" >&$fd_original_err
          set -u
          ;;
        E)
          set +u
          eval "$debug_expression" >&$fd_original_err
          set -u
          ;;
        f)
          read -p "Deep Find: " debug_search <&$fd_original_in
          if [ "${debug_search:-}" ]; then
            debug_search=${debug_search//\\/\\\\}
            debug_search=${debug_search//\$/\\\$}
            debug_prev_search=$debug_search
            debug_search_deep=t
            debug_r=0
            debug_long_command=t
          fi
          ;;
        F)
          if [ $debug_expanded_search == t ]; then
            echo "Expanded search is now off" >&$fd_original_err
            debug_expanded_search=f
          else
            echo "Expanded search is now on" >&$fd_original_err
            debug_expanded_search=t
          fi
          ;;
        h)
          if [ $debug_highlight == t ]; then
            echo "Syntax highlighting is now off" >&$fd_original_err
            debug_path_to_source_file=$raw_debug_path_to_source_file
            debug_highlight=f
          else
            echo "Syntax highlighting is now on" >&$fd_original_err
            debug_path_to_source_file=$highlighted_source
            debug_highlight=t
          fi
          ;;
        i)
          debug_r=0
          debug_max_depth=$((debug_current_depth+1))
          ;;
        j)
          read -p "Shallow Find: " debug_search <&$fd_original_in
          if [ "${debug_search:-}" ]; then
            debug_search=${debug_search//\\/\\\\}
            debug_search=${debug_search//\$/\\\$}
            debug_prev_search=$debug_search
            debug_search_deep=f
            debug_r=0
            debug_long_command=t
          fi
          ;;
        k)
          echo "Skipping..." >&$fd_original_err
          debug_r=1
          ;;
        l)
          [ $debug_list_dir == none ] && echo >&$fd_original_err
          [ $debug_list_dir == backwards ] && let debug_list_offset+=20
          debug_display_source
          let debug_list_offset+=20
          debug_list_dir=forwards
          ;;
        L)
          [ $debug_list_dir == forwards ] && let debug_list_offset-=20
          let debug_list_offset-=20
          debug_display_source
          debug_list_dir=backwards
          ;;
        n)
          debug_r=0
          debug_max_depth=$debug_current_depth
          debug_step_to_next_line=t
          ;;
        N)
          debug_r=0
          debug_max_depth=$debug_current_depth
          debug_step_to_later_line=t
          ;;
        o)
          echo "Stepping out of current function..." >&$fd_original_err
          debug_max_depth=$((debug_current_depth-1))
          debug_r=0
          debug_long_command=t
          ;;
        p)
          local fixed_command
          fixed_command=${raw_display_command}
          fixed_command=${fixed_command//\\\$/\\\\\$}
          fixed_command=${fixed_command//\$(/\\\$(}
          fixed_command=${fixed_command//\"/\\\"}
          set +u
          eval "echo \"$fixed_command\"" >&$fd_original_err
          set -u
          ;;
        P)
          local fixed_command
          fixed_command=${raw_display_command}
          fixed_command=${fixed_command//\\\$/\\\\\$}
          fixed_command=${fixed_command//\"/\\\"}
          fixed_command=${fixed_command//\$/\\\$}
          fixed_command=${fixed_command//\[/\$(\[}
          fixed_command=${fixed_command//]/] && echo true || echo false)}
          set +u
          eval "echo \"$fixed_command\"" >&$fd_original_err
          set -u
          ;;
        q) 
          debug_exit=t
          if [ -f "$debug_out_path" ]; then
            rm "$debug_out_path"
          fi
          exit 1
          ;;
        r)
          echo "Rewinding..." >&$fd_original_err
          debug_rewind=t
          debug_r=0
          ;;
        s)
          debug_r=0
          debug_max_depth=$debug_current_depth
          debug_step_to_next_line=f
          ;;
        S)
          start_frame=2 stack_trace
          ;;
        w)
          read -p "Watch: " debug_watch <&$fd_original_in
          ;;
        x)
          if [ $debug_expansion == 1 ]; then
            echo "Command expansion is now off" >&$fd_original_err
            debug_expansion=0
          else
            echo "Short command expansion is now on" >&$fd_original_err
            debug_expansion=1
          fi
          ;;
        X)
          if [ $debug_expansion == 2 ]; then
            echo "Command expansion is now off" >&$fd_original_err
            debug_expansion=0
          else
            echo "Extended command expansion is now on" >&$fd_original_err
            debug_expansion=2
          fi
          ;;
        =)
          debug_stop_at="$raw_debug_path_to_source_file $debug_line_num"
          debug_r=0
          debug_long_command=t
          debug_step_to_next_line=f
          ;;
        \])
          let debug_max_depth=debug_current_depth+10
          debug_step_to_next_function=t
          debug_r=0
          ;;
        .)
          if [ "${debug_prev_search:-}" ]; then
            debug_search=${debug_prev_search:-}
            debug_r=0
            debug_long_command=t
          else
            echo "No previous search." >&$fd_original_err
          fi
          ;;
        *)
          echo >&$fd_original_err
          echo "a  display array" >&$fd_original_err
          echo "c  list 10 lines of source code before and after current line" >&$fd_original_err
          echo "C  continue execution without stopping" >&$fd_original_err
          echo "d  display an expression with variables substituted" >&$fd_original_err
          echo "D  repeat last display command" >&$fd_original_err
          echo "e  evaluate an expression" >&$fd_original_err
          echo "E  repeat last eval expression command" >&$fd_original_err
          echo "f  continue until a line contains the substring given" >&$fd_original_err
          echo "F  toggle expanded search mode, which enables searching on evaluated string expressions" >&$fd_original_err
          echo "h  toggle syntax highlighting" >&$fd_original_err
          echo "i  next instruction, stepping into function calls" >&$fd_original_err
          echo "j  jump ahead: shallow substring find" >&$fd_original_err
          echo "k  skip current command" >&$fd_original_err
          echo "l  list next 20 lines of source code" >&$fd_original_err
          echo "L  list previous 20 lines of source code" >&$fd_original_err
          echo "n  next line of code (even if it resolves to several different statements)," >&$fd_original_err
          echo "     not stepping into function calls" >&$fd_original_err
          echo "N  continue executing until we reach a line later than the current line, completing loops if needed" >&$fd_original_err
          echo "o  step out from the current function" >&$fd_original_err
          echo "p  print evaluated variables" >&$fd_original_err
          echo "P  print evaluated conditional tests" >&$fd_original_err
          echo "q  quit: exit the program entirely" >&$fd_original_err
          echo "r  rewind: go back to the start of the last looping / try block" >&$fd_original_err
          echo "s  execute next small statement, even if multiple statements are on a line," >&$fd_original_err
          echo "     not stepping into function calls" >&$fd_original_err
          echo "S  show stack trace" >&$fd_original_err
          echo "w  set or clear current watched variable" >&$fd_original_err
          echo "x  toggle expanded command mode. If on, will expand each *short* command that is executed" >&$fd_original_err
          echo "X  toggle extended expanded command mode. If on, will expand *all* commands that are executed" >&$fd_original_err
          echo "=  continue until the current line is reached again" >&$fd_original_err
          echo "]  continue until we reach a different function" >&$fd_original_err
          echo ".  continue until a line contains the previously searched substring given" >&$fd_original_err
          ;;
      esac
    #fi
  done

  if [ $debug_expansion -gt 0 ]; then
    rm "$debug_fifo_path" &>/dev/null
    mkfifo "$debug_fifo_path"
    debug_expansion_clean "$debug_fifo_path" >"$debug_out_path" &
    debug_expansion_pid=$!
    exec {fd_bash_trace}>"$debug_fifo_path"
    BASH_XTRACEFD=$fd_bash_trace
  fi

  return $debug_r
}

set_return_code() {
  return $1
}

if [ ! "${debug_highlight:-}" ]; then
  if which source-highlight >/dev/null; then
    debug_highlight=t
  else
    debug_highlight=f
  fi
fi

if [ $debug_highlight == t ]; then
  if ! which source-highlight >/dev/null; then
    err "You set debug_highlight=t, but are missing the highlight command."
    err "You can use 'brew install highlight' to install it if you want."
    exit 1
  fi

  rm -rf $tmp_folder/debug_highlight &>/dev/null
  mkdir -p $tmp_folder/debug_highlight || exit 1
fi

reserve_tmp_file() {
  local var=$1; shift
  local base=${1:-$var}; shift
  
  local internal_tmp_file=$(mktemp $tmp_folder/$base.$$.XXXXXX)
  eval "$var=$internal_tmp_file"
  eval "cleanup_on_exit+='rm ${internal_tmp_file} &>/dev/null || true;'"
}

debug_start() {
  debug_dir=$PWD
  debug_display=${debug_display:-none}
  debug_exit=${debug_exit:-f}
  debug_expanded_search=${debug_expanded_search:-f}
  debug_expansion=${debug_expansion:-0}
  debug_expression=${debug_expression:-echo none}
  debug_last_location=${debug_last_location:-}
  debug_list_dir=${debug_list_dir:-none}
  debug_list_offset=${debug_list_offset:-0}
  debug_long_command=${debug_long_command:-f}
  debug_max_depth=${debug_max_depth:-99}
  debug_prev_line=${debug_prev_line:-0}
  debug_prev_search=${debug_prev_search:-}
  debug_prev_function=${debug_prev_function:-none}
  debug_rewind=${debug_rewind:-f}
  debug_search=${debug_search:-}
  debug_search_deep=${debug_search_deep:-t}
  debug_step_to_next_line=${debug_step_to_next_line:-f}
  debug_step_to_later_line=${debug_step_to_later_line:-f}
  debug_step_to_next_function=${debug_step_to_next_function:-f}
  debug_stop_at=${debug_stop_at:-}
  debug_watch=${debug_watch:-}

  reserve_tmp_file debug_fifo_path || exit 1
  reserve_tmp_file debug_out_path || exit 1

  shopt -s extdebug
  trap '
       set +x
       if [[ ! "${FUNCNAME[0]:-none}" =~ ^(echo_align|trace|run)$ ]]; then
         debug_trap "${BASH_SOURCE[0]}" "${LINENO[0]}" "${FUNCNAME[0]:-none}" "${BASH_COMMAND}" "$@"
         debug_rc=$?
         [ $debug_rewind == t ] && continue
         [ $debug_exit == t ] && exit 1
         [ $debug_expansion -gt 0 -a -n "${debug_expansion_pid:-}" ] && set -x
         set_return_code $debug_rc
       else
         true
       fi
       ' DEBUG
}

get_overlap() {
  local i
  result=
  for ((i=0; i<${#1}; i++)); do
    [ "${1:$i:1}" != "${2:$i:1}" ] && break
    result+=${1:$i:1}
  done
}

load_extension() {
  local extension_folder=$1
  [ -d "$extension_folder/handlers" ] && handler_path=( "$extension_folder/handlers" "${handler_path[@]}" )
  [ -d "$extension_folder/archetypes" ] && archetype_path=( "$extension_folder/archetypes" "${archetype_path[@]}" )
}

load_extensions() {
  local extension_folder f=$1
  if [ -d "$f/extensions" ]; then
    for extension_folder in $(find -L "$f/extensions" -mindepth 1 -maxdepth 1 -type d | sort); do
      load_extension "$extension_folder"
    done
  fi
  return 0
}

init_context() {
  handler_path=( "$SIMPLETON_REPO/handlers" )
  archetype_path=( "$SIMPLETON_REPO/archetypes" )
  load_extensions "$SIMPLETON_REPO"
  return 0
}

load_context() {

  local f=$1 
  local parent=${f%/*}
  [ "${#parent}" -gt 1 ] && (load_context "$parent" || return 1)
  load_extensions "$f"

  if [ -d "$f/handlers" ]; then
    handler_path=( "$f/handlers" "${handler_path[@]}" )
  fi

  local extension_folder
  if [ -f "$f/simpleton-extensions" ]; then
    for extension_folder in $(<$f/simpleton-extensions); do
      extension_folder="$SIMPLETON_REPO/../$extension_folder"
      if [ -d "$extension_folder" ]; then
        load_extension "$extension_folder" 
      else
        err "Missing extension: $extension_folder (required by $f/simpleton-extensions)"
        return 1
      fi
    done
  fi

  [ -f "$f/context" ] && source "$f/context"

  return 0

}

if [ "${debug:-f}" == t -o -n "${debug_search:-}" ]; then
  debug_prev_search=${debug_prev_search:-${debug_search:-}}
  debug_start
fi


