#!/bin/bash

dim_description='The environment (e.g. e1, e2)'
possibilities='all us india e1 e2 e2i e3 e31 e32 e33 e31i e32i'

# input: value result_var
# output: *result_var
expand_members() {
local result=

case "$value" in
  all)
    result='e1 e2 e3'
  ;;
  e3*)
    result='e3'
  ;;
  e2*)
    result='e2'
  ;;
  us)
    result='e1 e2 e3'
  ;;
  ind*)
    result='e2 e3'
  ;;
  e1)
    result=$value
  ;;
esac

eval "$result_var='$result'"
}
