#!/bin/bash

expand_dim() {
local dimension=$1; shift
local dimension_plural=${dimension}s; shift
local value=${!dimension:-${!dimension_plural:-}}
[ -z "$value" ] && return 1

case "$value" in
  e1|e2)
    : 
  ;;
  e3|e31|e32|e33)
    value=e3
  ;;
  *)
    err "Invalid value for $dimension: $value"
    err "Value must be one of: e1 e2 e3"
    return 1
  ;;
esac

eval "$dimension_plural=\$value"
return 0
}
