#!/bin/bash

type -t dna_delete >/dev/null && return 0

dna_delete() {

local subject=$(realpath -s $1)
local real=$(realpath $subject)

begin_function

  local cube=
  if [[ -L $subject ]]; then
    get_cube ${subject%/*} || fail
  else
    get_cube $subject || fail
  fi

  if [[ "$cube" ]]; then
    if [[ $cube == $subject ]]; then
      # is_cube
      trace $log_info "Removing cube ${cube##*/work/}"
      maybe rm -r $subject || fail
    else
      # is_in_cube
      local rest=${subject#$cube/}
      local part=${rest%%/*}
      case $rest in
        up)
          incomplete "$rest"
        ;;
        up/*)
          trace $log_info "Removing upstream dependency $rest from cube ${cube##*/work/}"
          local f
          begin_for f in $(find1 $subject/down); doo
            if [[ "$(realpath $f)" == $cube ]]; then
              maybe rm $f || fail
            fi
          end_for
          maybe rm $subject || fail
        ;;
        */*)
          incomplete "$rest"
        ;;
        *)
          incomplete "$rest"
        ;;
      esac
    fi
  fi

end_function
handle_return

}
