#!/bin/bash

handle() {

local subject=$1
trace 0 "Cleaning $subject"

begin_function

if [ "${deep_clean:-f}" == t ]; then
  local f
  for f in $(find "$subject" -mindepth 1 -maxdepth 1 -type d -not -name out -not -name .git | sort); do
    handle "$f" || fail
  done
fi

if [ -e "$subject/out" ]; then
  rm -rf "$subject/out" || fail
fi

end_function
handle_return

}